// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v4.25.2
// source: astro.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 开始校准
type ReqStartCalibration struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ReqStartCalibration) Reset() {
	*x = ReqStartCalibration{}
	if protoimpl.UnsafeEnabled {
		mi := &file_astro_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqStartCalibration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqStartCalibration) ProtoMessage() {}

func (x *ReqStartCalibration) ProtoReflect() protoreflect.Message {
	mi := &file_astro_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqStartCalibration.ProtoReflect.Descriptor instead.
func (*ReqStartCalibration) Descriptor() ([]byte, []int) {
	return file_astro_proto_rawDescGZIP(), []int{0}
}

// 停止校准
type ReqStopCalibration struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ReqStopCalibration) Reset() {
	*x = ReqStopCalibration{}
	if protoimpl.UnsafeEnabled {
		mi := &file_astro_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqStopCalibration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqStopCalibration) ProtoMessage() {}

func (x *ReqStopCalibration) ProtoReflect() protoreflect.Message {
	mi := &file_astro_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqStopCalibration.ProtoReflect.Descriptor instead.
func (*ReqStopCalibration) Descriptor() ([]byte, []int) {
	return file_astro_proto_rawDescGZIP(), []int{1}
}

// Goto深空天体
type ReqGotoDSO struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ra         float64 `protobuf:"fixed64,1,opt,name=ra,proto3" json:"ra,omitempty"`
	Dec        float64 `protobuf:"fixed64,2,opt,name=dec,proto3" json:"dec,omitempty"`
	TargetName string  `protobuf:"bytes,3,opt,name=target_name,json=targetName,proto3" json:"target_name,omitempty"`
}

func (x *ReqGotoDSO) Reset() {
	*x = ReqGotoDSO{}
	if protoimpl.UnsafeEnabled {
		mi := &file_astro_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqGotoDSO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqGotoDSO) ProtoMessage() {}

func (x *ReqGotoDSO) ProtoReflect() protoreflect.Message {
	mi := &file_astro_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqGotoDSO.ProtoReflect.Descriptor instead.
func (*ReqGotoDSO) Descriptor() ([]byte, []int) {
	return file_astro_proto_rawDescGZIP(), []int{2}
}

func (x *ReqGotoDSO) GetRa() float64 {
	if x != nil {
		return x.Ra
	}
	return 0
}

func (x *ReqGotoDSO) GetDec() float64 {
	if x != nil {
		return x.Dec
	}
	return 0
}

func (x *ReqGotoDSO) GetTargetName() string {
	if x != nil {
		return x.TargetName
	}
	return ""
}

// Goto太阳系
type ReqGotoSolarSystem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Index      int32   `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Lon        float64 `protobuf:"fixed64,2,opt,name=lon,proto3" json:"lon,omitempty"`
	Lat        float64 `protobuf:"fixed64,3,opt,name=lat,proto3" json:"lat,omitempty"`
	TargetName string  `protobuf:"bytes,4,opt,name=target_name,json=targetName,proto3" json:"target_name,omitempty"`
}

func (x *ReqGotoSolarSystem) Reset() {
	*x = ReqGotoSolarSystem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_astro_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqGotoSolarSystem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqGotoSolarSystem) ProtoMessage() {}

func (x *ReqGotoSolarSystem) ProtoReflect() protoreflect.Message {
	mi := &file_astro_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqGotoSolarSystem.ProtoReflect.Descriptor instead.
func (*ReqGotoSolarSystem) Descriptor() ([]byte, []int) {
	return file_astro_proto_rawDescGZIP(), []int{3}
}

func (x *ReqGotoSolarSystem) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *ReqGotoSolarSystem) GetLon() float64 {
	if x != nil {
		return x.Lon
	}
	return 0
}

func (x *ReqGotoSolarSystem) GetLat() float64 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *ReqGotoSolarSystem) GetTargetName() string {
	if x != nil {
		return x.TargetName
	}
	return ""
}

// 停止Goto
type ReqStopGoto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ReqStopGoto) Reset() {
	*x = ReqStopGoto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_astro_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqStopGoto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqStopGoto) ProtoMessage() {}

func (x *ReqStopGoto) ProtoReflect() protoreflect.Message {
	mi := &file_astro_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqStopGoto.ProtoReflect.Descriptor instead.
func (*ReqStopGoto) Descriptor() ([]byte, []int) {
	return file_astro_proto_rawDescGZIP(), []int{4}
}

// 开始叠图
type ReqCaptureRawLiveStacking struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ReqCaptureRawLiveStacking) Reset() {
	*x = ReqCaptureRawLiveStacking{}
	if protoimpl.UnsafeEnabled {
		mi := &file_astro_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqCaptureRawLiveStacking) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqCaptureRawLiveStacking) ProtoMessage() {}

func (x *ReqCaptureRawLiveStacking) ProtoReflect() protoreflect.Message {
	mi := &file_astro_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqCaptureRawLiveStacking.ProtoReflect.Descriptor instead.
func (*ReqCaptureRawLiveStacking) Descriptor() ([]byte, []int) {
	return file_astro_proto_rawDescGZIP(), []int{5}
}

// 停止叠图
type ReqStopCaptureRawLiveStacking struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ReqStopCaptureRawLiveStacking) Reset() {
	*x = ReqStopCaptureRawLiveStacking{}
	if protoimpl.UnsafeEnabled {
		mi := &file_astro_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqStopCaptureRawLiveStacking) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqStopCaptureRawLiveStacking) ProtoMessage() {}

func (x *ReqStopCaptureRawLiveStacking) ProtoReflect() protoreflect.Message {
	mi := &file_astro_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqStopCaptureRawLiveStacking.ProtoReflect.Descriptor instead.
func (*ReqStopCaptureRawLiveStacking) Descriptor() ([]byte, []int) {
	return file_astro_proto_rawDescGZIP(), []int{6}
}

// 查询暗场进度
type ReqCheckDarkFrame struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ReqCheckDarkFrame) Reset() {
	*x = ReqCheckDarkFrame{}
	if protoimpl.UnsafeEnabled {
		mi := &file_astro_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqCheckDarkFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqCheckDarkFrame) ProtoMessage() {}

func (x *ReqCheckDarkFrame) ProtoReflect() protoreflect.Message {
	mi := &file_astro_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqCheckDarkFrame.ProtoReflect.Descriptor instead.
func (*ReqCheckDarkFrame) Descriptor() ([]byte, []int) {
	return file_astro_proto_rawDescGZIP(), []int{7}
}

// 暗场进度返回
type ResCheckDarkFrame struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Progress int32 `protobuf:"varint,1,opt,name=progress,proto3" json:"progress,omitempty"`
	Code     int32 `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
}

func (x *ResCheckDarkFrame) Reset() {
	*x = ResCheckDarkFrame{}
	if protoimpl.UnsafeEnabled {
		mi := &file_astro_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResCheckDarkFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResCheckDarkFrame) ProtoMessage() {}

func (x *ResCheckDarkFrame) ProtoReflect() protoreflect.Message {
	mi := &file_astro_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResCheckDarkFrame.ProtoReflect.Descriptor instead.
func (*ResCheckDarkFrame) Descriptor() ([]byte, []int) {
	return file_astro_proto_rawDescGZIP(), []int{8}
}

func (x *ResCheckDarkFrame) GetProgress() int32 {
	if x != nil {
		return x.Progress
	}
	return 0
}

func (x *ResCheckDarkFrame) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

// 开始拍摄暗场
type ReqCaptureDarkFrame struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Reshoot int32 `protobuf:"varint,1,opt,name=reshoot,proto3" json:"reshoot,omitempty"`
}

func (x *ReqCaptureDarkFrame) Reset() {
	*x = ReqCaptureDarkFrame{}
	if protoimpl.UnsafeEnabled {
		mi := &file_astro_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqCaptureDarkFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqCaptureDarkFrame) ProtoMessage() {}

func (x *ReqCaptureDarkFrame) ProtoReflect() protoreflect.Message {
	mi := &file_astro_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqCaptureDarkFrame.ProtoReflect.Descriptor instead.
func (*ReqCaptureDarkFrame) Descriptor() ([]byte, []int) {
	return file_astro_proto_rawDescGZIP(), []int{9}
}

func (x *ReqCaptureDarkFrame) GetReshoot() int32 {
	if x != nil {
		return x.Reshoot
	}
	return 0
}

// 停止拍摄暗场
type ReqStopCaptureDarkFrame struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ReqStopCaptureDarkFrame) Reset() {
	*x = ReqStopCaptureDarkFrame{}
	if protoimpl.UnsafeEnabled {
		mi := &file_astro_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqStopCaptureDarkFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqStopCaptureDarkFrame) ProtoMessage() {}

func (x *ReqStopCaptureDarkFrame) ProtoReflect() protoreflect.Message {
	mi := &file_astro_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqStopCaptureDarkFrame.ProtoReflect.Descriptor instead.
func (*ReqStopCaptureDarkFrame) Descriptor() ([]byte, []int) {
	return file_astro_proto_rawDescGZIP(), []int{10}
}

// GO LIVE接口
type ReqGoLive struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ReqGoLive) Reset() {
	*x = ReqGoLive{}
	if protoimpl.UnsafeEnabled {
		mi := &file_astro_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqGoLive) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqGoLive) ProtoMessage() {}

func (x *ReqGoLive) ProtoReflect() protoreflect.Message {
	mi := &file_astro_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqGoLive.ProtoReflect.Descriptor instead.
func (*ReqGoLive) Descriptor() ([]byte, []int) {
	return file_astro_proto_rawDescGZIP(), []int{11}
}

// 开始日月跟踪
type ReqTrackSpecialTarget struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Index int32   `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Lon   float64 `protobuf:"fixed64,2,opt,name=lon,proto3" json:"lon,omitempty"`
	Lat   float64 `protobuf:"fixed64,3,opt,name=lat,proto3" json:"lat,omitempty"`
}

func (x *ReqTrackSpecialTarget) Reset() {
	*x = ReqTrackSpecialTarget{}
	if protoimpl.UnsafeEnabled {
		mi := &file_astro_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqTrackSpecialTarget) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqTrackSpecialTarget) ProtoMessage() {}

func (x *ReqTrackSpecialTarget) ProtoReflect() protoreflect.Message {
	mi := &file_astro_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqTrackSpecialTarget.ProtoReflect.Descriptor instead.
func (*ReqTrackSpecialTarget) Descriptor() ([]byte, []int) {
	return file_astro_proto_rawDescGZIP(), []int{12}
}

func (x *ReqTrackSpecialTarget) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *ReqTrackSpecialTarget) GetLon() float64 {
	if x != nil {
		return x.Lon
	}
	return 0
}

func (x *ReqTrackSpecialTarget) GetLat() float64 {
	if x != nil {
		return x.Lat
	}
	return 0
}

// 停止日月跟踪
type ReqStopTrackSpecialTarget struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ReqStopTrackSpecialTarget) Reset() {
	*x = ReqStopTrackSpecialTarget{}
	if protoimpl.UnsafeEnabled {
		mi := &file_astro_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqStopTrackSpecialTarget) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqStopTrackSpecialTarget) ProtoMessage() {}

func (x *ReqStopTrackSpecialTarget) ProtoReflect() protoreflect.Message {
	mi := &file_astro_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqStopTrackSpecialTarget.ProtoReflect.Descriptor instead.
func (*ReqStopTrackSpecialTarget) Descriptor() ([]byte, []int) {
	return file_astro_proto_rawDescGZIP(), []int{13}
}

var File_astro_proto protoreflect.FileDescriptor

var file_astro_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x61, 0x73, 0x74, 0x72, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x15, 0x0a,
	0x13, 0x52, 0x65, 0x71, 0x53, 0x74, 0x61, 0x72, 0x74, 0x43, 0x61, 0x6c, 0x69, 0x62, 0x72, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x22, 0x14, 0x0a, 0x12, 0x52, 0x65, 0x71, 0x53, 0x74, 0x6f, 0x70, 0x43,
	0x61, 0x6c, 0x69, 0x62, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x4f, 0x0a, 0x0a, 0x52, 0x65,
	0x71, 0x47, 0x6f, 0x74, 0x6f, 0x44, 0x53, 0x4f, 0x12, 0x0e, 0x0a, 0x02, 0x72, 0x61, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x01, 0x52, 0x02, 0x72, 0x61, 0x12, 0x10, 0x0a, 0x03, 0x64, 0x65, 0x63, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x03, 0x64, 0x65, 0x63, 0x12, 0x1f, 0x0a, 0x0b, 0x74, 0x61,
	0x72, 0x67, 0x65, 0x74, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0a, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x6f, 0x0a, 0x12, 0x52,
	0x65, 0x71, 0x47, 0x6f, 0x74, 0x6f, 0x53, 0x6f, 0x6c, 0x61, 0x72, 0x53, 0x79, 0x73, 0x74, 0x65,
	0x6d, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x10, 0x0a, 0x03, 0x6c, 0x6f, 0x6e, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x01, 0x52, 0x03, 0x6c, 0x6f, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x6c, 0x61, 0x74,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x03, 0x6c, 0x61, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x74,
	0x61, 0x72, 0x67, 0x65, 0x74, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0a, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x0d, 0x0a, 0x0b,
	0x52, 0x65, 0x71, 0x53, 0x74, 0x6f, 0x70, 0x47, 0x6f, 0x74, 0x6f, 0x22, 0x1b, 0x0a, 0x19, 0x52,
	0x65, 0x71, 0x43, 0x61, 0x70, 0x74, 0x75, 0x72, 0x65, 0x52, 0x61, 0x77, 0x4c, 0x69, 0x76, 0x65,
	0x53, 0x74, 0x61, 0x63, 0x6b, 0x69, 0x6e, 0x67, 0x22, 0x1f, 0x0a, 0x1d, 0x52, 0x65, 0x71, 0x53,
	0x74, 0x6f, 0x70, 0x43, 0x61, 0x70, 0x74, 0x75, 0x72, 0x65, 0x52, 0x61, 0x77, 0x4c, 0x69, 0x76,
	0x65, 0x53, 0x74, 0x61, 0x63, 0x6b, 0x69, 0x6e, 0x67, 0x22, 0x13, 0x0a, 0x11, 0x52, 0x65, 0x71,
	0x43, 0x68, 0x65, 0x63, 0x6b, 0x44, 0x61, 0x72, 0x6b, 0x46, 0x72, 0x61, 0x6d, 0x65, 0x22, 0x43,
	0x0a, 0x11, 0x52, 0x65, 0x73, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x44, 0x61, 0x72, 0x6b, 0x46, 0x72,
	0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x12,
	0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63,
	0x6f, 0x64, 0x65, 0x22, 0x2f, 0x0a, 0x13, 0x52, 0x65, 0x71, 0x43, 0x61, 0x70, 0x74, 0x75, 0x72,
	0x65, 0x44, 0x61, 0x72, 0x6b, 0x46, 0x72, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x72, 0x65,
	0x73, 0x68, 0x6f, 0x6f, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x72, 0x65, 0x73,
	0x68, 0x6f, 0x6f, 0x74, 0x22, 0x19, 0x0a, 0x17, 0x52, 0x65, 0x71, 0x53, 0x74, 0x6f, 0x70, 0x43,
	0x61, 0x70, 0x74, 0x75, 0x72, 0x65, 0x44, 0x61, 0x72, 0x6b, 0x46, 0x72, 0x61, 0x6d, 0x65, 0x22,
	0x0b, 0x0a, 0x09, 0x52, 0x65, 0x71, 0x47, 0x6f, 0x4c, 0x69, 0x76, 0x65, 0x22, 0x51, 0x0a, 0x15,
	0x52, 0x65, 0x71, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x53, 0x70, 0x65, 0x63, 0x69, 0x61, 0x6c, 0x54,
	0x61, 0x72, 0x67, 0x65, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x10, 0x0a, 0x03, 0x6c,
	0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x03, 0x6c, 0x6f, 0x6e, 0x12, 0x10, 0x0a,
	0x03, 0x6c, 0x61, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x03, 0x6c, 0x61, 0x74, 0x22,
	0x1b, 0x0a, 0x19, 0x52, 0x65, 0x71, 0x53, 0x74, 0x6f, 0x70, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x53,
	0x70, 0x65, 0x63, 0x69, 0x61, 0x6c, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x42, 0x1b, 0x5a, 0x19,
	0x76, 0x70, 0x72, 0x65, 0x6e, 0x6e, 0x65, 0x72, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x64, 0x77, 0x61,
	0x72, 0x66, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_astro_proto_rawDescOnce sync.Once
	file_astro_proto_rawDescData = file_astro_proto_rawDesc
)

func file_astro_proto_rawDescGZIP() []byte {
	file_astro_proto_rawDescOnce.Do(func() {
		file_astro_proto_rawDescData = protoimpl.X.CompressGZIP(file_astro_proto_rawDescData)
	})
	return file_astro_proto_rawDescData
}

var file_astro_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_astro_proto_goTypes = []interface{}{
	(*ReqStartCalibration)(nil),           // 0: ReqStartCalibration
	(*ReqStopCalibration)(nil),            // 1: ReqStopCalibration
	(*ReqGotoDSO)(nil),                    // 2: ReqGotoDSO
	(*ReqGotoSolarSystem)(nil),            // 3: ReqGotoSolarSystem
	(*ReqStopGoto)(nil),                   // 4: ReqStopGoto
	(*ReqCaptureRawLiveStacking)(nil),     // 5: ReqCaptureRawLiveStacking
	(*ReqStopCaptureRawLiveStacking)(nil), // 6: ReqStopCaptureRawLiveStacking
	(*ReqCheckDarkFrame)(nil),             // 7: ReqCheckDarkFrame
	(*ResCheckDarkFrame)(nil),             // 8: ResCheckDarkFrame
	(*ReqCaptureDarkFrame)(nil),           // 9: ReqCaptureDarkFrame
	(*ReqStopCaptureDarkFrame)(nil),       // 10: ReqStopCaptureDarkFrame
	(*ReqGoLive)(nil),                     // 11: ReqGoLive
	(*ReqTrackSpecialTarget)(nil),         // 12: ReqTrackSpecialTarget
	(*ReqStopTrackSpecialTarget)(nil),     // 13: ReqStopTrackSpecialTarget
}
var file_astro_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_astro_proto_init() }
func file_astro_proto_init() {
	if File_astro_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_astro_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqStartCalibration); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_astro_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqStopCalibration); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_astro_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqGotoDSO); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_astro_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqGotoSolarSystem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_astro_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqStopGoto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_astro_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqCaptureRawLiveStacking); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_astro_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqStopCaptureRawLiveStacking); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_astro_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqCheckDarkFrame); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_astro_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResCheckDarkFrame); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_astro_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqCaptureDarkFrame); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_astro_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqStopCaptureDarkFrame); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_astro_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqGoLive); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_astro_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqTrackSpecialTarget); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_astro_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqStopTrackSpecialTarget); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_astro_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_astro_proto_goTypes,
		DependencyIndexes: file_astro_proto_depIdxs,
		MessageInfos:      file_astro_proto_msgTypes,
	}.Build()
	File_astro_proto = out.File
	file_astro_proto_rawDesc = nil
	file_astro_proto_goTypes = nil
	file_astro_proto_depIdxs = nil
}
