// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v4.25.2
// source: base.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WsMajorVersion int32

const (
	WsMajorVersion_WS_MAJOR_VERSION_UNKNOWN WsMajorVersion = 0
	WsMajorVersion_WS_MAJOR_VERSION_NUMBER  WsMajorVersion = 1
)

// Enum value maps for WsMajorVersion.
var (
	WsMajorVersion_name = map[int32]string{
		0: "WS_MAJOR_VERSION_UNKNOWN",
		1: "WS_MAJOR_VERSION_NUMBER",
	}
	WsMajorVersion_value = map[string]int32{
		"WS_MAJOR_VERSION_UNKNOWN": 0,
		"WS_MAJOR_VERSION_NUMBER":  1,
	}
)

func (x WsMajorVersion) Enum() *WsMajorVersion {
	p := new(WsMajorVersion)
	*p = x
	return p
}

func (x WsMajorVersion) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WsMajorVersion) Descriptor() protoreflect.EnumDescriptor {
	return file_base_proto_enumTypes[0].Descriptor()
}

func (WsMajorVersion) Type() protoreflect.EnumType {
	return &file_base_proto_enumTypes[0]
}

func (x WsMajorVersion) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WsMajorVersion.Descriptor instead.
func (WsMajorVersion) EnumDescriptor() ([]byte, []int) {
	return file_base_proto_rawDescGZIP(), []int{0}
}

type WsMinorVersion int32

const (
	WsMinorVersion_WS_MINOR_VERSION_UNKNOWN WsMinorVersion = 0
	WsMinorVersion_WS_MINOR_VERSION_NUMBER  WsMinorVersion = 1
)

// Enum value maps for WsMinorVersion.
var (
	WsMinorVersion_name = map[int32]string{
		0: "WS_MINOR_VERSION_UNKNOWN",
		1: "WS_MINOR_VERSION_NUMBER",
	}
	WsMinorVersion_value = map[string]int32{
		"WS_MINOR_VERSION_UNKNOWN": 0,
		"WS_MINOR_VERSION_NUMBER":  1,
	}
)

func (x WsMinorVersion) Enum() *WsMinorVersion {
	p := new(WsMinorVersion)
	*p = x
	return p
}

func (x WsMinorVersion) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WsMinorVersion) Descriptor() protoreflect.EnumDescriptor {
	return file_base_proto_enumTypes[1].Descriptor()
}

func (WsMinorVersion) Type() protoreflect.EnumType {
	return &file_base_proto_enumTypes[1]
}

func (x WsMinorVersion) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WsMinorVersion.Descriptor instead.
func (WsMinorVersion) EnumDescriptor() ([]byte, []int) {
	return file_base_proto_rawDescGZIP(), []int{1}
}

type WsPacket struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MajorVersion uint32 `protobuf:"varint,1,opt,name=major_version,json=majorVersion,proto3" json:"major_version,omitempty"` //协议主版本
	MinorVersion uint32 `protobuf:"varint,2,opt,name=minor_version,json=minorVersion,proto3" json:"minor_version,omitempty"` //协议次版本
	DeviceId     uint32 `protobuf:"varint,3,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`             //设备ID
	ModuleId     uint32 `protobuf:"varint,4,opt,name=module_id,json=moduleId,proto3" json:"module_id,omitempty"`             //模块ID
	Cmd          uint32 `protobuf:"varint,5,opt,name=cmd,proto3" json:"cmd,omitempty"`                                       //指令
	Type         uint32 `protobuf:"varint,6,opt,name=type,proto3" json:"type,omitempty"`                                     //消息类型 0：请求 1：应答 2：通知 3：响应
	Data         []byte `protobuf:"bytes,7,opt,name=data,proto3" json:"data,omitempty"`                                      //请求、响应数据，对应具体的业务接口
	ClientId     string `protobuf:"bytes,8,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`              //ws客户端id
}

func (x *WsPacket) Reset() {
	*x = WsPacket{}
	if protoimpl.UnsafeEnabled {
		mi := &file_base_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WsPacket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WsPacket) ProtoMessage() {}

func (x *WsPacket) ProtoReflect() protoreflect.Message {
	mi := &file_base_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WsPacket.ProtoReflect.Descriptor instead.
func (*WsPacket) Descriptor() ([]byte, []int) {
	return file_base_proto_rawDescGZIP(), []int{0}
}

func (x *WsPacket) GetMajorVersion() uint32 {
	if x != nil {
		return x.MajorVersion
	}
	return 0
}

func (x *WsPacket) GetMinorVersion() uint32 {
	if x != nil {
		return x.MinorVersion
	}
	return 0
}

func (x *WsPacket) GetDeviceId() uint32 {
	if x != nil {
		return x.DeviceId
	}
	return 0
}

func (x *WsPacket) GetModuleId() uint32 {
	if x != nil {
		return x.ModuleId
	}
	return 0
}

func (x *WsPacket) GetCmd() uint32 {
	if x != nil {
		return x.Cmd
	}
	return 0
}

func (x *WsPacket) GetType() uint32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *WsPacket) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *WsPacket) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

type ComResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code int32 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
}

func (x *ComResponse) Reset() {
	*x = ComResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_base_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ComResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComResponse) ProtoMessage() {}

func (x *ComResponse) ProtoReflect() protoreflect.Message {
	mi := &file_base_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComResponse.ProtoReflect.Descriptor instead.
func (*ComResponse) Descriptor() ([]byte, []int) {
	return file_base_proto_rawDescGZIP(), []int{1}
}

func (x *ComResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

type ComResWithInt struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value int32 `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	Code  int32 `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
}

func (x *ComResWithInt) Reset() {
	*x = ComResWithInt{}
	if protoimpl.UnsafeEnabled {
		mi := &file_base_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ComResWithInt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComResWithInt) ProtoMessage() {}

func (x *ComResWithInt) ProtoReflect() protoreflect.Message {
	mi := &file_base_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComResWithInt.ProtoReflect.Descriptor instead.
func (*ComResWithInt) Descriptor() ([]byte, []int) {
	return file_base_proto_rawDescGZIP(), []int{2}
}

func (x *ComResWithInt) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *ComResWithInt) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

type ComResWithDouble struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value float64 `protobuf:"fixed64,1,opt,name=value,proto3" json:"value,omitempty"`
	Code  int32   `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
}

func (x *ComResWithDouble) Reset() {
	*x = ComResWithDouble{}
	if protoimpl.UnsafeEnabled {
		mi := &file_base_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ComResWithDouble) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComResWithDouble) ProtoMessage() {}

func (x *ComResWithDouble) ProtoReflect() protoreflect.Message {
	mi := &file_base_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComResWithDouble.ProtoReflect.Descriptor instead.
func (*ComResWithDouble) Descriptor() ([]byte, []int) {
	return file_base_proto_rawDescGZIP(), []int{3}
}

func (x *ComResWithDouble) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *ComResWithDouble) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

type CommonParam struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HasAuto       bool    `protobuf:"varint,1,opt,name=hasAuto,proto3" json:"hasAuto,omitempty"`
	AutoMode      int32   `protobuf:"varint,2,opt,name=auto_mode,json=autoMode,proto3" json:"auto_mode,omitempty"`
	Id            int32   `protobuf:"varint,3,opt,name=id,proto3" json:"id,omitempty"`
	ModeIndex     int32   `protobuf:"varint,4,opt,name=mode_index,json=modeIndex,proto3" json:"mode_index,omitempty"`
	Index         int32   `protobuf:"varint,5,opt,name=index,proto3" json:"index,omitempty"`
	ContinueValue float64 `protobuf:"fixed64,6,opt,name=continue_value,json=continueValue,proto3" json:"continue_value,omitempty"`
}

func (x *CommonParam) Reset() {
	*x = CommonParam{}
	if protoimpl.UnsafeEnabled {
		mi := &file_base_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommonParam) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommonParam) ProtoMessage() {}

func (x *CommonParam) ProtoReflect() protoreflect.Message {
	mi := &file_base_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommonParam.ProtoReflect.Descriptor instead.
func (*CommonParam) Descriptor() ([]byte, []int) {
	return file_base_proto_rawDescGZIP(), []int{4}
}

func (x *CommonParam) GetHasAuto() bool {
	if x != nil {
		return x.HasAuto
	}
	return false
}

func (x *CommonParam) GetAutoMode() int32 {
	if x != nil {
		return x.AutoMode
	}
	return 0
}

func (x *CommonParam) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CommonParam) GetModeIndex() int32 {
	if x != nil {
		return x.ModeIndex
	}
	return 0
}

func (x *CommonParam) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *CommonParam) GetContinueValue() float64 {
	if x != nil {
		return x.ContinueValue
	}
	return 0
}

var File_base_proto protoreflect.FileDescriptor

var file_base_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xe5, 0x01, 0x0a,
	0x08, 0x57, 0x73, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x12, 0x23, 0x0a, 0x0d, 0x6d, 0x61, 0x6a,
	0x6f, 0x72, 0x5f, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x0c, 0x6d, 0x61, 0x6a, 0x6f, 0x72, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x23,
	0x0a, 0x0d, 0x6d, 0x69, 0x6e, 0x6f, 0x72, 0x5f, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0c, 0x6d, 0x69, 0x6e, 0x6f, 0x72, 0x56, 0x65, 0x72, 0x73,
	0x69, 0x6f, 0x6e, 0x12, 0x1b, 0x0a, 0x09, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x69, 0x64,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x64,
	0x12, 0x1b, 0x0a, 0x09, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x08, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x49, 0x64, 0x12, 0x10, 0x0a,
	0x03, 0x63, 0x6d, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x63, 0x6d, 0x64, 0x12,
	0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x74,
	0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x6c, 0x69, 0x65, 0x6e,
	0x74, 0x5f, 0x69, 0x64, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x6c, 0x69, 0x65,
	0x6e, 0x74, 0x49, 0x64, 0x22, 0x21, 0x0a, 0x0b, 0x43, 0x6f, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x22, 0x39, 0x0a, 0x0d, 0x43, 0x6f, 0x6d, 0x52, 0x65,
	0x73, 0x57, 0x69, 0x74, 0x68, 0x49, 0x6e, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f,
	0x64, 0x65, 0x22, 0x3c, 0x0a, 0x10, 0x43, 0x6f, 0x6d, 0x52, 0x65, 0x73, 0x57, 0x69, 0x74, 0x68,
	0x44, 0x6f, 0x75, 0x62, 0x6c, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65,
	0x22, 0xb0, 0x01, 0x0a, 0x0b, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x50, 0x61, 0x72, 0x61, 0x6d,
	0x12, 0x18, 0x0a, 0x07, 0x68, 0x61, 0x73, 0x41, 0x75, 0x74, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x07, 0x68, 0x61, 0x73, 0x41, 0x75, 0x74, 0x6f, 0x12, 0x1b, 0x0a, 0x09, 0x61, 0x75,
	0x74, 0x6f, 0x5f, 0x6d, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x61,
	0x75, 0x74, 0x6f, 0x4d, 0x6f, 0x64, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x6d, 0x6f, 0x64, 0x65, 0x5f,
	0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x6d, 0x6f, 0x64,
	0x65, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x25, 0x0a, 0x0e,
	0x63, 0x6f, 0x6e, 0x74, 0x69, 0x6e, 0x75, 0x65, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x01, 0x52, 0x0d, 0x63, 0x6f, 0x6e, 0x74, 0x69, 0x6e, 0x75, 0x65, 0x56, 0x61,
	0x6c, 0x75, 0x65, 0x2a, 0x4b, 0x0a, 0x0e, 0x57, 0x73, 0x4d, 0x61, 0x6a, 0x6f, 0x72, 0x56, 0x65,
	0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x1c, 0x0a, 0x18, 0x57, 0x53, 0x5f, 0x4d, 0x41, 0x4a, 0x4f,
	0x52, 0x5f, 0x56, 0x45, 0x52, 0x53, 0x49, 0x4f, 0x4e, 0x5f, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57,
	0x4e, 0x10, 0x00, 0x12, 0x1b, 0x0a, 0x17, 0x57, 0x53, 0x5f, 0x4d, 0x41, 0x4a, 0x4f, 0x52, 0x5f,
	0x56, 0x45, 0x52, 0x53, 0x49, 0x4f, 0x4e, 0x5f, 0x4e, 0x55, 0x4d, 0x42, 0x45, 0x52, 0x10, 0x01,
	0x2a, 0x4b, 0x0a, 0x0e, 0x57, 0x73, 0x4d, 0x69, 0x6e, 0x6f, 0x72, 0x56, 0x65, 0x72, 0x73, 0x69,
	0x6f, 0x6e, 0x12, 0x1c, 0x0a, 0x18, 0x57, 0x53, 0x5f, 0x4d, 0x49, 0x4e, 0x4f, 0x52, 0x5f, 0x56,
	0x45, 0x52, 0x53, 0x49, 0x4f, 0x4e, 0x5f, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00,
	0x12, 0x1b, 0x0a, 0x17, 0x57, 0x53, 0x5f, 0x4d, 0x49, 0x4e, 0x4f, 0x52, 0x5f, 0x56, 0x45, 0x52,
	0x53, 0x49, 0x4f, 0x4e, 0x5f, 0x4e, 0x55, 0x4d, 0x42, 0x45, 0x52, 0x10, 0x01, 0x42, 0x1b, 0x5a,
	0x19, 0x76, 0x70, 0x72, 0x65, 0x6e, 0x6e, 0x65, 0x72, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x64, 0x77,
	0x61, 0x72, 0x66, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_base_proto_rawDescOnce sync.Once
	file_base_proto_rawDescData = file_base_proto_rawDesc
)

func file_base_proto_rawDescGZIP() []byte {
	file_base_proto_rawDescOnce.Do(func() {
		file_base_proto_rawDescData = protoimpl.X.CompressGZIP(file_base_proto_rawDescData)
	})
	return file_base_proto_rawDescData
}

var file_base_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_base_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_base_proto_goTypes = []interface{}{
	(WsMajorVersion)(0),      // 0: WsMajorVersion
	(WsMinorVersion)(0),      // 1: WsMinorVersion
	(*WsPacket)(nil),         // 2: WsPacket
	(*ComResponse)(nil),      // 3: ComResponse
	(*ComResWithInt)(nil),    // 4: ComResWithInt
	(*ComResWithDouble)(nil), // 5: ComResWithDouble
	(*CommonParam)(nil),      // 6: CommonParam
}
var file_base_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_base_proto_init() }
func file_base_proto_init() {
	if File_base_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_base_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WsPacket); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_base_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ComResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_base_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ComResWithInt); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_base_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ComResWithDouble); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_base_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommonParam); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_base_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_base_proto_goTypes,
		DependencyIndexes: file_base_proto_depIdxs,
		EnumInfos:         file_base_proto_enumTypes,
		MessageInfos:      file_base_proto_msgTypes,
	}.Build()
	File_base_proto = out.File
	file_base_proto_rawDesc = nil
	file_base_proto_goTypes = nil
	file_base_proto_depIdxs = nil
}
