// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v4.25.2
// source: camera.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 打开摄像头
type ReqOpenCamera struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Binning bool `protobuf:"varint,1,opt,name=binning,proto3" json:"binning,omitempty"`
}

func (x *ReqOpenCamera) Reset() {
	*x = ReqOpenCamera{}
	if protoimpl.UnsafeEnabled {
		mi := &file_camera_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqOpenCamera) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqOpenCamera) ProtoMessage() {}

func (x *ReqOpenCamera) ProtoReflect() protoreflect.Message {
	mi := &file_camera_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqOpenCamera.ProtoReflect.Descriptor instead.
func (*ReqOpenCamera) Descriptor() ([]byte, []int) {
	return file_camera_proto_rawDescGZIP(), []int{0}
}

func (x *ReqOpenCamera) GetBinning() bool {
	if x != nil {
		return x.Binning
	}
	return false
}

// 关闭摄像头
type ReqCloseCamera struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ReqCloseCamera) Reset() {
	*x = ReqCloseCamera{}
	if protoimpl.UnsafeEnabled {
		mi := &file_camera_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqCloseCamera) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqCloseCamera) ProtoMessage() {}

func (x *ReqCloseCamera) ProtoReflect() protoreflect.Message {
	mi := &file_camera_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqCloseCamera.ProtoReflect.Descriptor instead.
func (*ReqCloseCamera) Descriptor() ([]byte, []int) {
	return file_camera_proto_rawDescGZIP(), []int{1}
}

// 拍照
type ReqPhoto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ReqPhoto) Reset() {
	*x = ReqPhoto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_camera_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqPhoto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqPhoto) ProtoMessage() {}

func (x *ReqPhoto) ProtoReflect() protoreflect.Message {
	mi := &file_camera_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqPhoto.ProtoReflect.Descriptor instead.
func (*ReqPhoto) Descriptor() ([]byte, []int) {
	return file_camera_proto_rawDescGZIP(), []int{2}
}

// 开始连拍
type ReqBurstPhoto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Count int32 `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
}

func (x *ReqBurstPhoto) Reset() {
	*x = ReqBurstPhoto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_camera_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqBurstPhoto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqBurstPhoto) ProtoMessage() {}

func (x *ReqBurstPhoto) ProtoReflect() protoreflect.Message {
	mi := &file_camera_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqBurstPhoto.ProtoReflect.Descriptor instead.
func (*ReqBurstPhoto) Descriptor() ([]byte, []int) {
	return file_camera_proto_rawDescGZIP(), []int{3}
}

func (x *ReqBurstPhoto) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

// 停止连拍
type ReqStopBurstPhoto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ReqStopBurstPhoto) Reset() {
	*x = ReqStopBurstPhoto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_camera_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqStopBurstPhoto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqStopBurstPhoto) ProtoMessage() {}

func (x *ReqStopBurstPhoto) ProtoReflect() protoreflect.Message {
	mi := &file_camera_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqStopBurstPhoto.ProtoReflect.Descriptor instead.
func (*ReqStopBurstPhoto) Descriptor() ([]byte, []int) {
	return file_camera_proto_rawDescGZIP(), []int{4}
}

// 开始录像
type ReqStartRecord struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ReqStartRecord) Reset() {
	*x = ReqStartRecord{}
	if protoimpl.UnsafeEnabled {
		mi := &file_camera_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqStartRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqStartRecord) ProtoMessage() {}

func (x *ReqStartRecord) ProtoReflect() protoreflect.Message {
	mi := &file_camera_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqStartRecord.ProtoReflect.Descriptor instead.
func (*ReqStartRecord) Descriptor() ([]byte, []int) {
	return file_camera_proto_rawDescGZIP(), []int{5}
}

// 停止录像
type ReqStopRecord struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ReqStopRecord) Reset() {
	*x = ReqStopRecord{}
	if protoimpl.UnsafeEnabled {
		mi := &file_camera_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqStopRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqStopRecord) ProtoMessage() {}

func (x *ReqStopRecord) ProtoReflect() protoreflect.Message {
	mi := &file_camera_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqStopRecord.ProtoReflect.Descriptor instead.
func (*ReqStopRecord) Descriptor() ([]byte, []int) {
	return file_camera_proto_rawDescGZIP(), []int{6}
}

// 设置曝光模式
type ReqSetExpMode struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mode int32 `protobuf:"varint,1,opt,name=mode,proto3" json:"mode,omitempty"`
}

func (x *ReqSetExpMode) Reset() {
	*x = ReqSetExpMode{}
	if protoimpl.UnsafeEnabled {
		mi := &file_camera_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqSetExpMode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqSetExpMode) ProtoMessage() {}

func (x *ReqSetExpMode) ProtoReflect() protoreflect.Message {
	mi := &file_camera_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqSetExpMode.ProtoReflect.Descriptor instead.
func (*ReqSetExpMode) Descriptor() ([]byte, []int) {
	return file_camera_proto_rawDescGZIP(), []int{7}
}

func (x *ReqSetExpMode) GetMode() int32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

// 获取曝光模式
type ReqGetExpMode struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ReqGetExpMode) Reset() {
	*x = ReqGetExpMode{}
	if protoimpl.UnsafeEnabled {
		mi := &file_camera_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqGetExpMode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqGetExpMode) ProtoMessage() {}

func (x *ReqGetExpMode) ProtoReflect() protoreflect.Message {
	mi := &file_camera_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqGetExpMode.ProtoReflect.Descriptor instead.
func (*ReqGetExpMode) Descriptor() ([]byte, []int) {
	return file_camera_proto_rawDescGZIP(), []int{8}
}

// 设置曝光
type ReqSetExp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Index int32 `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
}

func (x *ReqSetExp) Reset() {
	*x = ReqSetExp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_camera_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqSetExp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqSetExp) ProtoMessage() {}

func (x *ReqSetExp) ProtoReflect() protoreflect.Message {
	mi := &file_camera_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqSetExp.ProtoReflect.Descriptor instead.
func (*ReqSetExp) Descriptor() ([]byte, []int) {
	return file_camera_proto_rawDescGZIP(), []int{9}
}

func (x *ReqSetExp) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

// 获取曝光
type ReqGetExp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ReqGetExp) Reset() {
	*x = ReqGetExp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_camera_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqGetExp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqGetExp) ProtoMessage() {}

func (x *ReqGetExp) ProtoReflect() protoreflect.Message {
	mi := &file_camera_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqGetExp.ProtoReflect.Descriptor instead.
func (*ReqGetExp) Descriptor() ([]byte, []int) {
	return file_camera_proto_rawDescGZIP(), []int{10}
}

// 设置增益模式
type ReqSetGainMode struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mode int32 `protobuf:"varint,1,opt,name=mode,proto3" json:"mode,omitempty"`
}

func (x *ReqSetGainMode) Reset() {
	*x = ReqSetGainMode{}
	if protoimpl.UnsafeEnabled {
		mi := &file_camera_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqSetGainMode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqSetGainMode) ProtoMessage() {}

func (x *ReqSetGainMode) ProtoReflect() protoreflect.Message {
	mi := &file_camera_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqSetGainMode.ProtoReflect.Descriptor instead.
func (*ReqSetGainMode) Descriptor() ([]byte, []int) {
	return file_camera_proto_rawDescGZIP(), []int{11}
}

func (x *ReqSetGainMode) GetMode() int32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

// 获取增益模式
type ReqGetGainMode struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ReqGetGainMode) Reset() {
	*x = ReqGetGainMode{}
	if protoimpl.UnsafeEnabled {
		mi := &file_camera_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqGetGainMode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqGetGainMode) ProtoMessage() {}

func (x *ReqGetGainMode) ProtoReflect() protoreflect.Message {
	mi := &file_camera_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqGetGainMode.ProtoReflect.Descriptor instead.
func (*ReqGetGainMode) Descriptor() ([]byte, []int) {
	return file_camera_proto_rawDescGZIP(), []int{12}
}

// 设置增益
type ReqSetGain struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Index int32 `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
}

func (x *ReqSetGain) Reset() {
	*x = ReqSetGain{}
	if protoimpl.UnsafeEnabled {
		mi := &file_camera_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqSetGain) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqSetGain) ProtoMessage() {}

func (x *ReqSetGain) ProtoReflect() protoreflect.Message {
	mi := &file_camera_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqSetGain.ProtoReflect.Descriptor instead.
func (*ReqSetGain) Descriptor() ([]byte, []int) {
	return file_camera_proto_rawDescGZIP(), []int{13}
}

func (x *ReqSetGain) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

// 获取增益
type ReqGetGain struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ReqGetGain) Reset() {
	*x = ReqGetGain{}
	if protoimpl.UnsafeEnabled {
		mi := &file_camera_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqGetGain) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqGetGain) ProtoMessage() {}

func (x *ReqGetGain) ProtoReflect() protoreflect.Message {
	mi := &file_camera_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqGetGain.ProtoReflect.Descriptor instead.
func (*ReqGetGain) Descriptor() ([]byte, []int) {
	return file_camera_proto_rawDescGZIP(), []int{14}
}

// 设置亮度
type ReqSetBrightness struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value int32 `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *ReqSetBrightness) Reset() {
	*x = ReqSetBrightness{}
	if protoimpl.UnsafeEnabled {
		mi := &file_camera_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqSetBrightness) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqSetBrightness) ProtoMessage() {}

func (x *ReqSetBrightness) ProtoReflect() protoreflect.Message {
	mi := &file_camera_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqSetBrightness.ProtoReflect.Descriptor instead.
func (*ReqSetBrightness) Descriptor() ([]byte, []int) {
	return file_camera_proto_rawDescGZIP(), []int{15}
}

func (x *ReqSetBrightness) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

// 获取亮度
type ReqGetBrightness struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ReqGetBrightness) Reset() {
	*x = ReqGetBrightness{}
	if protoimpl.UnsafeEnabled {
		mi := &file_camera_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqGetBrightness) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqGetBrightness) ProtoMessage() {}

func (x *ReqGetBrightness) ProtoReflect() protoreflect.Message {
	mi := &file_camera_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqGetBrightness.ProtoReflect.Descriptor instead.
func (*ReqGetBrightness) Descriptor() ([]byte, []int) {
	return file_camera_proto_rawDescGZIP(), []int{16}
}

// 设置对比度
type ReqSetContrast struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value int32 `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *ReqSetContrast) Reset() {
	*x = ReqSetContrast{}
	if protoimpl.UnsafeEnabled {
		mi := &file_camera_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqSetContrast) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqSetContrast) ProtoMessage() {}

func (x *ReqSetContrast) ProtoReflect() protoreflect.Message {
	mi := &file_camera_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqSetContrast.ProtoReflect.Descriptor instead.
func (*ReqSetContrast) Descriptor() ([]byte, []int) {
	return file_camera_proto_rawDescGZIP(), []int{17}
}

func (x *ReqSetContrast) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

// 获取对比度
type ReqGetContrast struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ReqGetContrast) Reset() {
	*x = ReqGetContrast{}
	if protoimpl.UnsafeEnabled {
		mi := &file_camera_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqGetContrast) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqGetContrast) ProtoMessage() {}

func (x *ReqGetContrast) ProtoReflect() protoreflect.Message {
	mi := &file_camera_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqGetContrast.ProtoReflect.Descriptor instead.
func (*ReqGetContrast) Descriptor() ([]byte, []int) {
	return file_camera_proto_rawDescGZIP(), []int{18}
}

// 设置色调
type ReqSetHue struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value int32 `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *ReqSetHue) Reset() {
	*x = ReqSetHue{}
	if protoimpl.UnsafeEnabled {
		mi := &file_camera_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqSetHue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqSetHue) ProtoMessage() {}

func (x *ReqSetHue) ProtoReflect() protoreflect.Message {
	mi := &file_camera_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqSetHue.ProtoReflect.Descriptor instead.
func (*ReqSetHue) Descriptor() ([]byte, []int) {
	return file_camera_proto_rawDescGZIP(), []int{19}
}

func (x *ReqSetHue) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

// 获取色调
type ReqGetHue struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ReqGetHue) Reset() {
	*x = ReqGetHue{}
	if protoimpl.UnsafeEnabled {
		mi := &file_camera_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqGetHue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqGetHue) ProtoMessage() {}

func (x *ReqGetHue) ProtoReflect() protoreflect.Message {
	mi := &file_camera_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqGetHue.ProtoReflect.Descriptor instead.
func (*ReqGetHue) Descriptor() ([]byte, []int) {
	return file_camera_proto_rawDescGZIP(), []int{20}
}

// 设置饱和度
type ReqSetSaturation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value int32 `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *ReqSetSaturation) Reset() {
	*x = ReqSetSaturation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_camera_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqSetSaturation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqSetSaturation) ProtoMessage() {}

func (x *ReqSetSaturation) ProtoReflect() protoreflect.Message {
	mi := &file_camera_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqSetSaturation.ProtoReflect.Descriptor instead.
func (*ReqSetSaturation) Descriptor() ([]byte, []int) {
	return file_camera_proto_rawDescGZIP(), []int{21}
}

func (x *ReqSetSaturation) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

// 获取饱和度
type ReqGetSaturation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ReqGetSaturation) Reset() {
	*x = ReqGetSaturation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_camera_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqGetSaturation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqGetSaturation) ProtoMessage() {}

func (x *ReqGetSaturation) ProtoReflect() protoreflect.Message {
	mi := &file_camera_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqGetSaturation.ProtoReflect.Descriptor instead.
func (*ReqGetSaturation) Descriptor() ([]byte, []int) {
	return file_camera_proto_rawDescGZIP(), []int{22}
}

// 设置锐度
type ReqSetSharpness struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value int32 `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *ReqSetSharpness) Reset() {
	*x = ReqSetSharpness{}
	if protoimpl.UnsafeEnabled {
		mi := &file_camera_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqSetSharpness) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqSetSharpness) ProtoMessage() {}

func (x *ReqSetSharpness) ProtoReflect() protoreflect.Message {
	mi := &file_camera_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqSetSharpness.ProtoReflect.Descriptor instead.
func (*ReqSetSharpness) Descriptor() ([]byte, []int) {
	return file_camera_proto_rawDescGZIP(), []int{23}
}

func (x *ReqSetSharpness) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

// 获取锐度
type ReqGetSharpness struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ReqGetSharpness) Reset() {
	*x = ReqGetSharpness{}
	if protoimpl.UnsafeEnabled {
		mi := &file_camera_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqGetSharpness) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqGetSharpness) ProtoMessage() {}

func (x *ReqGetSharpness) ProtoReflect() protoreflect.Message {
	mi := &file_camera_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqGetSharpness.ProtoReflect.Descriptor instead.
func (*ReqGetSharpness) Descriptor() ([]byte, []int) {
	return file_camera_proto_rawDescGZIP(), []int{24}
}

// 设置白平衡模式
type ReqSetWBMode struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mode int32 `protobuf:"varint,1,opt,name=mode,proto3" json:"mode,omitempty"`
}

func (x *ReqSetWBMode) Reset() {
	*x = ReqSetWBMode{}
	if protoimpl.UnsafeEnabled {
		mi := &file_camera_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqSetWBMode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqSetWBMode) ProtoMessage() {}

func (x *ReqSetWBMode) ProtoReflect() protoreflect.Message {
	mi := &file_camera_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqSetWBMode.ProtoReflect.Descriptor instead.
func (*ReqSetWBMode) Descriptor() ([]byte, []int) {
	return file_camera_proto_rawDescGZIP(), []int{25}
}

func (x *ReqSetWBMode) GetMode() int32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

// 获取白平衡模式
type ReqGetWBMode struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ReqGetWBMode) Reset() {
	*x = ReqGetWBMode{}
	if protoimpl.UnsafeEnabled {
		mi := &file_camera_proto_msgTypes[26]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqGetWBMode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqGetWBMode) ProtoMessage() {}

func (x *ReqGetWBMode) ProtoReflect() protoreflect.Message {
	mi := &file_camera_proto_msgTypes[26]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqGetWBMode.ProtoReflect.Descriptor instead.
func (*ReqGetWBMode) Descriptor() ([]byte, []int) {
	return file_camera_proto_rawDescGZIP(), []int{26}
}

// 设置白平衡场景
type ReqSetWBSence struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value int32 `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *ReqSetWBSence) Reset() {
	*x = ReqSetWBSence{}
	if protoimpl.UnsafeEnabled {
		mi := &file_camera_proto_msgTypes[27]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqSetWBSence) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqSetWBSence) ProtoMessage() {}

func (x *ReqSetWBSence) ProtoReflect() protoreflect.Message {
	mi := &file_camera_proto_msgTypes[27]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqSetWBSence.ProtoReflect.Descriptor instead.
func (*ReqSetWBSence) Descriptor() ([]byte, []int) {
	return file_camera_proto_rawDescGZIP(), []int{27}
}

func (x *ReqSetWBSence) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

// 获取白平衡场景
type ReqGetWBSence struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ReqGetWBSence) Reset() {
	*x = ReqGetWBSence{}
	if protoimpl.UnsafeEnabled {
		mi := &file_camera_proto_msgTypes[28]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqGetWBSence) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqGetWBSence) ProtoMessage() {}

func (x *ReqGetWBSence) ProtoReflect() protoreflect.Message {
	mi := &file_camera_proto_msgTypes[28]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqGetWBSence.ProtoReflect.Descriptor instead.
func (*ReqGetWBSence) Descriptor() ([]byte, []int) {
	return file_camera_proto_rawDescGZIP(), []int{28}
}

// 设置白平衡色温
type ReqSetWBCT struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Index int32 `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
}

func (x *ReqSetWBCT) Reset() {
	*x = ReqSetWBCT{}
	if protoimpl.UnsafeEnabled {
		mi := &file_camera_proto_msgTypes[29]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqSetWBCT) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqSetWBCT) ProtoMessage() {}

func (x *ReqSetWBCT) ProtoReflect() protoreflect.Message {
	mi := &file_camera_proto_msgTypes[29]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqSetWBCT.ProtoReflect.Descriptor instead.
func (*ReqSetWBCT) Descriptor() ([]byte, []int) {
	return file_camera_proto_rawDescGZIP(), []int{29}
}

func (x *ReqSetWBCT) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

// 获取白平衡色温
type ReqGetWBCT struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ReqGetWBCT) Reset() {
	*x = ReqGetWBCT{}
	if protoimpl.UnsafeEnabled {
		mi := &file_camera_proto_msgTypes[30]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqGetWBCT) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqGetWBCT) ProtoMessage() {}

func (x *ReqGetWBCT) ProtoReflect() protoreflect.Message {
	mi := &file_camera_proto_msgTypes[30]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqGetWBCT.ProtoReflect.Descriptor instead.
func (*ReqGetWBCT) Descriptor() ([]byte, []int) {
	return file_camera_proto_rawDescGZIP(), []int{30}
}

// 设置IRCUT
type ReqSetIrCut struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value int32 `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *ReqSetIrCut) Reset() {
	*x = ReqSetIrCut{}
	if protoimpl.UnsafeEnabled {
		mi := &file_camera_proto_msgTypes[31]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqSetIrCut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqSetIrCut) ProtoMessage() {}

func (x *ReqSetIrCut) ProtoReflect() protoreflect.Message {
	mi := &file_camera_proto_msgTypes[31]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqSetIrCut.ProtoReflect.Descriptor instead.
func (*ReqSetIrCut) Descriptor() ([]byte, []int) {
	return file_camera_proto_rawDescGZIP(), []int{31}
}

func (x *ReqSetIrCut) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

// 获取IRCUT状态
type ReqGetIrcut struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ReqGetIrcut) Reset() {
	*x = ReqGetIrcut{}
	if protoimpl.UnsafeEnabled {
		mi := &file_camera_proto_msgTypes[32]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqGetIrcut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqGetIrcut) ProtoMessage() {}

func (x *ReqGetIrcut) ProtoReflect() protoreflect.Message {
	mi := &file_camera_proto_msgTypes[32]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqGetIrcut.ProtoReflect.Descriptor instead.
func (*ReqGetIrcut) Descriptor() ([]byte, []int) {
	return file_camera_proto_rawDescGZIP(), []int{32}
}

// 开始延时摄影
type ReqStartTimeLapse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ReqStartTimeLapse) Reset() {
	*x = ReqStartTimeLapse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_camera_proto_msgTypes[33]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqStartTimeLapse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqStartTimeLapse) ProtoMessage() {}

func (x *ReqStartTimeLapse) ProtoReflect() protoreflect.Message {
	mi := &file_camera_proto_msgTypes[33]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqStartTimeLapse.ProtoReflect.Descriptor instead.
func (*ReqStartTimeLapse) Descriptor() ([]byte, []int) {
	return file_camera_proto_rawDescGZIP(), []int{33}
}

// 停止延时摄影
type ReqStopTimeLapse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ReqStopTimeLapse) Reset() {
	*x = ReqStopTimeLapse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_camera_proto_msgTypes[34]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqStopTimeLapse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqStopTimeLapse) ProtoMessage() {}

func (x *ReqStopTimeLapse) ProtoReflect() protoreflect.Message {
	mi := &file_camera_proto_msgTypes[34]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqStopTimeLapse.ProtoReflect.Descriptor instead.
func (*ReqStopTimeLapse) Descriptor() ([]byte, []int) {
	return file_camera_proto_rawDescGZIP(), []int{34}
}

// 设置所有参数
type ReqSetAllParams struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ExpMode     int32 `protobuf:"varint,1,opt,name=exp_mode,json=expMode,proto3" json:"exp_mode,omitempty"`
	ExpIndex    int32 `protobuf:"varint,2,opt,name=exp_index,json=expIndex,proto3" json:"exp_index,omitempty"`
	GainMode    int32 `protobuf:"varint,3,opt,name=gain_mode,json=gainMode,proto3" json:"gain_mode,omitempty"`
	GainIndex   int32 `protobuf:"varint,4,opt,name=gain_index,json=gainIndex,proto3" json:"gain_index,omitempty"`
	IrcutValue  int32 `protobuf:"varint,5,opt,name=ircut_value,json=ircutValue,proto3" json:"ircut_value,omitempty"`
	WbMode      int32 `protobuf:"varint,6,opt,name=wb_mode,json=wbMode,proto3" json:"wb_mode,omitempty"`
	WbIndexType int32 `protobuf:"varint,7,opt,name=wb_index_type,json=wbIndexType,proto3" json:"wb_index_type,omitempty"`
	WbIndex     int32 `protobuf:"varint,8,opt,name=wb_index,json=wbIndex,proto3" json:"wb_index,omitempty"`
	Brightness  int32 `protobuf:"varint,9,opt,name=brightness,proto3" json:"brightness,omitempty"`
	Contrast    int32 `protobuf:"varint,10,opt,name=contrast,proto3" json:"contrast,omitempty"`
	Hue         int32 `protobuf:"varint,11,opt,name=hue,proto3" json:"hue,omitempty"`
	Saturation  int32 `protobuf:"varint,12,opt,name=saturation,proto3" json:"saturation,omitempty"`
	Sharpness   int32 `protobuf:"varint,13,opt,name=sharpness,proto3" json:"sharpness,omitempty"`
	JpgQuality  int32 `protobuf:"varint,14,opt,name=jpg_quality,json=jpgQuality,proto3" json:"jpg_quality,omitempty"`
}

func (x *ReqSetAllParams) Reset() {
	*x = ReqSetAllParams{}
	if protoimpl.UnsafeEnabled {
		mi := &file_camera_proto_msgTypes[35]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqSetAllParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqSetAllParams) ProtoMessage() {}

func (x *ReqSetAllParams) ProtoReflect() protoreflect.Message {
	mi := &file_camera_proto_msgTypes[35]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqSetAllParams.ProtoReflect.Descriptor instead.
func (*ReqSetAllParams) Descriptor() ([]byte, []int) {
	return file_camera_proto_rawDescGZIP(), []int{35}
}

func (x *ReqSetAllParams) GetExpMode() int32 {
	if x != nil {
		return x.ExpMode
	}
	return 0
}

func (x *ReqSetAllParams) GetExpIndex() int32 {
	if x != nil {
		return x.ExpIndex
	}
	return 0
}

func (x *ReqSetAllParams) GetGainMode() int32 {
	if x != nil {
		return x.GainMode
	}
	return 0
}

func (x *ReqSetAllParams) GetGainIndex() int32 {
	if x != nil {
		return x.GainIndex
	}
	return 0
}

func (x *ReqSetAllParams) GetIrcutValue() int32 {
	if x != nil {
		return x.IrcutValue
	}
	return 0
}

func (x *ReqSetAllParams) GetWbMode() int32 {
	if x != nil {
		return x.WbMode
	}
	return 0
}

func (x *ReqSetAllParams) GetWbIndexType() int32 {
	if x != nil {
		return x.WbIndexType
	}
	return 0
}

func (x *ReqSetAllParams) GetWbIndex() int32 {
	if x != nil {
		return x.WbIndex
	}
	return 0
}

func (x *ReqSetAllParams) GetBrightness() int32 {
	if x != nil {
		return x.Brightness
	}
	return 0
}

func (x *ReqSetAllParams) GetContrast() int32 {
	if x != nil {
		return x.Contrast
	}
	return 0
}

func (x *ReqSetAllParams) GetHue() int32 {
	if x != nil {
		return x.Hue
	}
	return 0
}

func (x *ReqSetAllParams) GetSaturation() int32 {
	if x != nil {
		return x.Saturation
	}
	return 0
}

func (x *ReqSetAllParams) GetSharpness() int32 {
	if x != nil {
		return x.Sharpness
	}
	return 0
}

func (x *ReqSetAllParams) GetJpgQuality() int32 {
	if x != nil {
		return x.JpgQuality
	}
	return 0
}

// 获取所有参数
type ReqGetAllParams struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ReqGetAllParams) Reset() {
	*x = ReqGetAllParams{}
	if protoimpl.UnsafeEnabled {
		mi := &file_camera_proto_msgTypes[36]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqGetAllParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqGetAllParams) ProtoMessage() {}

func (x *ReqGetAllParams) ProtoReflect() protoreflect.Message {
	mi := &file_camera_proto_msgTypes[36]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqGetAllParams.ProtoReflect.Descriptor instead.
func (*ReqGetAllParams) Descriptor() ([]byte, []int) {
	return file_camera_proto_rawDescGZIP(), []int{36}
}

// 返回所有参数结果
type ResGetAllParams struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AllParams []*CommonParam `protobuf:"bytes,1,rep,name=all_params,json=allParams,proto3" json:"all_params,omitempty"`
	Code      int32          `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
}

func (x *ResGetAllParams) Reset() {
	*x = ResGetAllParams{}
	if protoimpl.UnsafeEnabled {
		mi := &file_camera_proto_msgTypes[37]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResGetAllParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResGetAllParams) ProtoMessage() {}

func (x *ResGetAllParams) ProtoReflect() protoreflect.Message {
	mi := &file_camera_proto_msgTypes[37]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResGetAllParams.ProtoReflect.Descriptor instead.
func (*ResGetAllParams) Descriptor() ([]byte, []int) {
	return file_camera_proto_rawDescGZIP(), []int{37}
}

func (x *ResGetAllParams) GetAllParams() []*CommonParam {
	if x != nil {
		return x.AllParams
	}
	return nil
}

func (x *ResGetAllParams) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

// 设置feature参数
type ReqSetFeatureParams struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Param *CommonParam `protobuf:"bytes,1,opt,name=param,proto3" json:"param,omitempty"`
}

func (x *ReqSetFeatureParams) Reset() {
	*x = ReqSetFeatureParams{}
	if protoimpl.UnsafeEnabled {
		mi := &file_camera_proto_msgTypes[38]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqSetFeatureParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqSetFeatureParams) ProtoMessage() {}

func (x *ReqSetFeatureParams) ProtoReflect() protoreflect.Message {
	mi := &file_camera_proto_msgTypes[38]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqSetFeatureParams.ProtoReflect.Descriptor instead.
func (*ReqSetFeatureParams) Descriptor() ([]byte, []int) {
	return file_camera_proto_rawDescGZIP(), []int{38}
}

func (x *ReqSetFeatureParams) GetParam() *CommonParam {
	if x != nil {
		return x.Param
	}
	return nil
}

// 获取所有feature参数
type ReqGetAllFeatureParams struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ReqGetAllFeatureParams) Reset() {
	*x = ReqGetAllFeatureParams{}
	if protoimpl.UnsafeEnabled {
		mi := &file_camera_proto_msgTypes[39]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqGetAllFeatureParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqGetAllFeatureParams) ProtoMessage() {}

func (x *ReqGetAllFeatureParams) ProtoReflect() protoreflect.Message {
	mi := &file_camera_proto_msgTypes[39]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqGetAllFeatureParams.ProtoReflect.Descriptor instead.
func (*ReqGetAllFeatureParams) Descriptor() ([]byte, []int) {
	return file_camera_proto_rawDescGZIP(), []int{39}
}

// 返回所有feature参数
type ResGetAllFeatureParams struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AllFeatureParams []*CommonParam `protobuf:"bytes,1,rep,name=all_feature_params,json=allFeatureParams,proto3" json:"all_feature_params,omitempty"`
	Code             int32          `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
}

func (x *ResGetAllFeatureParams) Reset() {
	*x = ResGetAllFeatureParams{}
	if protoimpl.UnsafeEnabled {
		mi := &file_camera_proto_msgTypes[40]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResGetAllFeatureParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResGetAllFeatureParams) ProtoMessage() {}

func (x *ResGetAllFeatureParams) ProtoReflect() protoreflect.Message {
	mi := &file_camera_proto_msgTypes[40]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResGetAllFeatureParams.ProtoReflect.Descriptor instead.
func (*ResGetAllFeatureParams) Descriptor() ([]byte, []int) {
	return file_camera_proto_rawDescGZIP(), []int{40}
}

func (x *ResGetAllFeatureParams) GetAllFeatureParams() []*CommonParam {
	if x != nil {
		return x.AllFeatureParams
	}
	return nil
}

func (x *ResGetAllFeatureParams) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

// 获取整机工作状态
type ReqGetSystemWorkingState struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ReqGetSystemWorkingState) Reset() {
	*x = ReqGetSystemWorkingState{}
	if protoimpl.UnsafeEnabled {
		mi := &file_camera_proto_msgTypes[41]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqGetSystemWorkingState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqGetSystemWorkingState) ProtoMessage() {}

func (x *ReqGetSystemWorkingState) ProtoReflect() protoreflect.Message {
	mi := &file_camera_proto_msgTypes[41]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqGetSystemWorkingState.ProtoReflect.Descriptor instead.
func (*ReqGetSystemWorkingState) Descriptor() ([]byte, []int) {
	return file_camera_proto_rawDescGZIP(), []int{41}
}

// 设置预览jpg质量
type ReqSetJpgQuality struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Quality int32 `protobuf:"varint,1,opt,name=quality,proto3" json:"quality,omitempty"`
}

func (x *ReqSetJpgQuality) Reset() {
	*x = ReqSetJpgQuality{}
	if protoimpl.UnsafeEnabled {
		mi := &file_camera_proto_msgTypes[42]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqSetJpgQuality) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqSetJpgQuality) ProtoMessage() {}

func (x *ReqSetJpgQuality) ProtoReflect() protoreflect.Message {
	mi := &file_camera_proto_msgTypes[42]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqSetJpgQuality.ProtoReflect.Descriptor instead.
func (*ReqSetJpgQuality) Descriptor() ([]byte, []int) {
	return file_camera_proto_rawDescGZIP(), []int{42}
}

func (x *ReqSetJpgQuality) GetQuality() int32 {
	if x != nil {
		return x.Quality
	}
	return 0
}

// 获取预览jpg质量
type ReqGetJpgQuality struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ReqGetJpgQuality) Reset() {
	*x = ReqGetJpgQuality{}
	if protoimpl.UnsafeEnabled {
		mi := &file_camera_proto_msgTypes[43]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqGetJpgQuality) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqGetJpgQuality) ProtoMessage() {}

func (x *ReqGetJpgQuality) ProtoReflect() protoreflect.Message {
	mi := &file_camera_proto_msgTypes[43]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqGetJpgQuality.ProtoReflect.Descriptor instead.
func (*ReqGetJpgQuality) Descriptor() ([]byte, []int) {
	return file_camera_proto_rawDescGZIP(), []int{43}
}

var File_camera_proto protoreflect.FileDescriptor

var file_camera_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x63, 0x61, 0x6d, 0x65, 0x72, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0a,
	0x62, 0x61, 0x73, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x29, 0x0a, 0x0d, 0x52, 0x65,
	0x71, 0x4f, 0x70, 0x65, 0x6e, 0x43, 0x61, 0x6d, 0x65, 0x72, 0x61, 0x12, 0x18, 0x0a, 0x07, 0x62,
	0x69, 0x6e, 0x6e, 0x69, 0x6e, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x62, 0x69,
	0x6e, 0x6e, 0x69, 0x6e, 0x67, 0x22, 0x10, 0x0a, 0x0e, 0x52, 0x65, 0x71, 0x43, 0x6c, 0x6f, 0x73,
	0x65, 0x43, 0x61, 0x6d, 0x65, 0x72, 0x61, 0x22, 0x0a, 0x0a, 0x08, 0x52, 0x65, 0x71, 0x50, 0x68,
	0x6f, 0x74, 0x6f, 0x22, 0x25, 0x0a, 0x0d, 0x52, 0x65, 0x71, 0x42, 0x75, 0x72, 0x73, 0x74, 0x50,
	0x68, 0x6f, 0x74, 0x6f, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x13, 0x0a, 0x11, 0x52, 0x65,
	0x71, 0x53, 0x74, 0x6f, 0x70, 0x42, 0x75, 0x72, 0x73, 0x74, 0x50, 0x68, 0x6f, 0x74, 0x6f, 0x22,
	0x10, 0x0a, 0x0e, 0x52, 0x65, 0x71, 0x53, 0x74, 0x61, 0x72, 0x74, 0x52, 0x65, 0x63, 0x6f, 0x72,
	0x64, 0x22, 0x0f, 0x0a, 0x0d, 0x52, 0x65, 0x71, 0x53, 0x74, 0x6f, 0x70, 0x52, 0x65, 0x63, 0x6f,
	0x72, 0x64, 0x22, 0x23, 0x0a, 0x0d, 0x52, 0x65, 0x71, 0x53, 0x65, 0x74, 0x45, 0x78, 0x70, 0x4d,
	0x6f, 0x64, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6d, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x04, 0x6d, 0x6f, 0x64, 0x65, 0x22, 0x0f, 0x0a, 0x0d, 0x52, 0x65, 0x71, 0x47, 0x65,
	0x74, 0x45, 0x78, 0x70, 0x4d, 0x6f, 0x64, 0x65, 0x22, 0x21, 0x0a, 0x09, 0x52, 0x65, 0x71, 0x53,
	0x65, 0x74, 0x45, 0x78, 0x70, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x22, 0x0b, 0x0a, 0x09, 0x52,
	0x65, 0x71, 0x47, 0x65, 0x74, 0x45, 0x78, 0x70, 0x22, 0x24, 0x0a, 0x0e, 0x52, 0x65, 0x71, 0x53,
	0x65, 0x74, 0x47, 0x61, 0x69, 0x6e, 0x4d, 0x6f, 0x64, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6d, 0x6f,
	0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x6d, 0x6f, 0x64, 0x65, 0x22, 0x10,
	0x0a, 0x0e, 0x52, 0x65, 0x71, 0x47, 0x65, 0x74, 0x47, 0x61, 0x69, 0x6e, 0x4d, 0x6f, 0x64, 0x65,
	0x22, 0x22, 0x0a, 0x0a, 0x52, 0x65, 0x71, 0x53, 0x65, 0x74, 0x47, 0x61, 0x69, 0x6e, 0x12, 0x14,
	0x0a, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x69,
	0x6e, 0x64, 0x65, 0x78, 0x22, 0x0c, 0x0a, 0x0a, 0x52, 0x65, 0x71, 0x47, 0x65, 0x74, 0x47, 0x61,
	0x69, 0x6e, 0x22, 0x28, 0x0a, 0x10, 0x52, 0x65, 0x71, 0x53, 0x65, 0x74, 0x42, 0x72, 0x69, 0x67,
	0x68, 0x74, 0x6e, 0x65, 0x73, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x12, 0x0a, 0x10,
	0x52, 0x65, 0x71, 0x47, 0x65, 0x74, 0x42, 0x72, 0x69, 0x67, 0x68, 0x74, 0x6e, 0x65, 0x73, 0x73,
	0x22, 0x26, 0x0a, 0x0e, 0x52, 0x65, 0x71, 0x53, 0x65, 0x74, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61,
	0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x10, 0x0a, 0x0e, 0x52, 0x65, 0x71, 0x47,
	0x65, 0x74, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x73, 0x74, 0x22, 0x21, 0x0a, 0x09, 0x52, 0x65,
	0x71, 0x53, 0x65, 0x74, 0x48, 0x75, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x0b, 0x0a,
	0x09, 0x52, 0x65, 0x71, 0x47, 0x65, 0x74, 0x48, 0x75, 0x65, 0x22, 0x28, 0x0a, 0x10, 0x52, 0x65,
	0x71, 0x53, 0x65, 0x74, 0x53, 0x61, 0x74, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x14,
	0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x22, 0x12, 0x0a, 0x10, 0x52, 0x65, 0x71, 0x47, 0x65, 0x74, 0x53, 0x61,
	0x74, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x27, 0x0a, 0x0f, 0x52, 0x65, 0x71, 0x53,
	0x65, 0x74, 0x53, 0x68, 0x61, 0x72, 0x70, 0x6e, 0x65, 0x73, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x22, 0x11, 0x0a, 0x0f, 0x52, 0x65, 0x71, 0x47, 0x65, 0x74, 0x53, 0x68, 0x61, 0x72, 0x70,
	0x6e, 0x65, 0x73, 0x73, 0x22, 0x22, 0x0a, 0x0c, 0x52, 0x65, 0x71, 0x53, 0x65, 0x74, 0x57, 0x42,
	0x4d, 0x6f, 0x64, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6d, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x04, 0x6d, 0x6f, 0x64, 0x65, 0x22, 0x0e, 0x0a, 0x0c, 0x52, 0x65, 0x71, 0x47,
	0x65, 0x74, 0x57, 0x42, 0x4d, 0x6f, 0x64, 0x65, 0x22, 0x25, 0x0a, 0x0d, 0x52, 0x65, 0x71, 0x53,
	0x65, 0x74, 0x57, 0x42, 0x53, 0x65, 0x6e, 0x63, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22,
	0x0f, 0x0a, 0x0d, 0x52, 0x65, 0x71, 0x47, 0x65, 0x74, 0x57, 0x42, 0x53, 0x65, 0x6e, 0x63, 0x65,
	0x22, 0x22, 0x0a, 0x0a, 0x52, 0x65, 0x71, 0x53, 0x65, 0x74, 0x57, 0x42, 0x43, 0x54, 0x12, 0x14,
	0x0a, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x69,
	0x6e, 0x64, 0x65, 0x78, 0x22, 0x0c, 0x0a, 0x0a, 0x52, 0x65, 0x71, 0x47, 0x65, 0x74, 0x57, 0x42,
	0x43, 0x54, 0x22, 0x23, 0x0a, 0x0b, 0x52, 0x65, 0x71, 0x53, 0x65, 0x74, 0x49, 0x72, 0x43, 0x75,
	0x74, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x0d, 0x0a, 0x0b, 0x52, 0x65, 0x71, 0x47, 0x65,
	0x74, 0x49, 0x72, 0x63, 0x75, 0x74, 0x22, 0x13, 0x0a, 0x11, 0x52, 0x65, 0x71, 0x53, 0x74, 0x61,
	0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x4c, 0x61, 0x70, 0x73, 0x65, 0x22, 0x12, 0x0a, 0x10, 0x52,
	0x65, 0x71, 0x53, 0x74, 0x6f, 0x70, 0x54, 0x69, 0x6d, 0x65, 0x4c, 0x61, 0x70, 0x73, 0x65, 0x22,
	0xab, 0x03, 0x0a, 0x0f, 0x52, 0x65, 0x71, 0x53, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x50, 0x61, 0x72,
	0x61, 0x6d, 0x73, 0x12, 0x19, 0x0a, 0x08, 0x65, 0x78, 0x70, 0x5f, 0x6d, 0x6f, 0x64, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x65, 0x78, 0x70, 0x4d, 0x6f, 0x64, 0x65, 0x12, 0x1b,
	0x0a, 0x09, 0x65, 0x78, 0x70, 0x5f, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x08, 0x65, 0x78, 0x70, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x1b, 0x0a, 0x09, 0x67,
	0x61, 0x69, 0x6e, 0x5f, 0x6d, 0x6f, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08,
	0x67, 0x61, 0x69, 0x6e, 0x4d, 0x6f, 0x64, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x67, 0x61, 0x69, 0x6e,
	0x5f, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x67, 0x61,
	0x69, 0x6e, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x1f, 0x0a, 0x0b, 0x69, 0x72, 0x63, 0x75, 0x74,
	0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x69, 0x72,
	0x63, 0x75, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x77, 0x62, 0x5f, 0x6d,
	0x6f, 0x64, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x77, 0x62, 0x4d, 0x6f, 0x64,
	0x65, 0x12, 0x22, 0x0a, 0x0d, 0x77, 0x62, 0x5f, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x5f, 0x74, 0x79,
	0x70, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x77, 0x62, 0x49, 0x6e, 0x64, 0x65,
	0x78, 0x54, 0x79, 0x70, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x77, 0x62, 0x5f, 0x69, 0x6e, 0x64, 0x65,
	0x78, 0x18, 0x08, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x77, 0x62, 0x49, 0x6e, 0x64, 0x65, 0x78,
	0x12, 0x1e, 0x0a, 0x0a, 0x62, 0x72, 0x69, 0x67, 0x68, 0x74, 0x6e, 0x65, 0x73, 0x73, 0x18, 0x09,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x62, 0x72, 0x69, 0x67, 0x68, 0x74, 0x6e, 0x65, 0x73, 0x73,
	0x12, 0x1a, 0x0a, 0x08, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x73, 0x74, 0x18, 0x0a, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x08, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03,
	0x68, 0x75, 0x65, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x68, 0x75, 0x65, 0x12, 0x1e,
	0x0a, 0x0a, 0x73, 0x61, 0x74, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x0c, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x0a, 0x73, 0x61, 0x74, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1c,
	0x0a, 0x09, 0x73, 0x68, 0x61, 0x72, 0x70, 0x6e, 0x65, 0x73, 0x73, 0x18, 0x0d, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x09, 0x73, 0x68, 0x61, 0x72, 0x70, 0x6e, 0x65, 0x73, 0x73, 0x12, 0x1f, 0x0a, 0x0b,
	0x6a, 0x70, 0x67, 0x5f, 0x71, 0x75, 0x61, 0x6c, 0x69, 0x74, 0x79, 0x18, 0x0e, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x0a, 0x6a, 0x70, 0x67, 0x51, 0x75, 0x61, 0x6c, 0x69, 0x74, 0x79, 0x22, 0x11, 0x0a,
	0x0f, 0x52, 0x65, 0x71, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73,
	0x22, 0x52, 0x0a, 0x0f, 0x52, 0x65, 0x73, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x50, 0x61, 0x72,
	0x61, 0x6d, 0x73, 0x12, 0x2b, 0x0a, 0x0a, 0x61, 0x6c, 0x6c, 0x5f, 0x70, 0x61, 0x72, 0x61, 0x6d,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e,
	0x50, 0x61, 0x72, 0x61, 0x6d, 0x52, 0x09, 0x61, 0x6c, 0x6c, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73,
	0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04,
	0x63, 0x6f, 0x64, 0x65, 0x22, 0x39, 0x0a, 0x13, 0x52, 0x65, 0x71, 0x53, 0x65, 0x74, 0x46, 0x65,
	0x61, 0x74, 0x75, 0x72, 0x65, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x12, 0x22, 0x0a, 0x05, 0x70,
	0x61, 0x72, 0x61, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x43, 0x6f, 0x6d,
	0x6d, 0x6f, 0x6e, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x52, 0x05, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x22,
	0x18, 0x0a, 0x16, 0x52, 0x65, 0x71, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x46, 0x65, 0x61, 0x74,
	0x75, 0x72, 0x65, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x22, 0x68, 0x0a, 0x16, 0x52, 0x65, 0x73,
	0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x46, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x50, 0x61, 0x72,
	0x61, 0x6d, 0x73, 0x12, 0x3a, 0x0a, 0x12, 0x61, 0x6c, 0x6c, 0x5f, 0x66, 0x65, 0x61, 0x74, 0x75,
	0x72, 0x65, 0x5f, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x0c, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x52, 0x10, 0x61,
	0x6c, 0x6c, 0x46, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x12,
	0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63,
	0x6f, 0x64, 0x65, 0x22, 0x1a, 0x0a, 0x18, 0x52, 0x65, 0x71, 0x47, 0x65, 0x74, 0x53, 0x79, 0x73,
	0x74, 0x65, 0x6d, 0x57, 0x6f, 0x72, 0x6b, 0x69, 0x6e, 0x67, 0x53, 0x74, 0x61, 0x74, 0x65, 0x22,
	0x2c, 0x0a, 0x10, 0x52, 0x65, 0x71, 0x53, 0x65, 0x74, 0x4a, 0x70, 0x67, 0x51, 0x75, 0x61, 0x6c,
	0x69, 0x74, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x71, 0x75, 0x61, 0x6c, 0x69, 0x74, 0x79, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x71, 0x75, 0x61, 0x6c, 0x69, 0x74, 0x79, 0x22, 0x12, 0x0a,
	0x10, 0x52, 0x65, 0x71, 0x47, 0x65, 0x74, 0x4a, 0x70, 0x67, 0x51, 0x75, 0x61, 0x6c, 0x69, 0x74,
	0x79, 0x42, 0x1b, 0x5a, 0x19, 0x76, 0x70, 0x72, 0x65, 0x6e, 0x6e, 0x65, 0x72, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x64, 0x77, 0x61, 0x72, 0x66, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_camera_proto_rawDescOnce sync.Once
	file_camera_proto_rawDescData = file_camera_proto_rawDesc
)

func file_camera_proto_rawDescGZIP() []byte {
	file_camera_proto_rawDescOnce.Do(func() {
		file_camera_proto_rawDescData = protoimpl.X.CompressGZIP(file_camera_proto_rawDescData)
	})
	return file_camera_proto_rawDescData
}

var file_camera_proto_msgTypes = make([]protoimpl.MessageInfo, 44)
var file_camera_proto_goTypes = []interface{}{
	(*ReqOpenCamera)(nil),            // 0: ReqOpenCamera
	(*ReqCloseCamera)(nil),           // 1: ReqCloseCamera
	(*ReqPhoto)(nil),                 // 2: ReqPhoto
	(*ReqBurstPhoto)(nil),            // 3: ReqBurstPhoto
	(*ReqStopBurstPhoto)(nil),        // 4: ReqStopBurstPhoto
	(*ReqStartRecord)(nil),           // 5: ReqStartRecord
	(*ReqStopRecord)(nil),            // 6: ReqStopRecord
	(*ReqSetExpMode)(nil),            // 7: ReqSetExpMode
	(*ReqGetExpMode)(nil),            // 8: ReqGetExpMode
	(*ReqSetExp)(nil),                // 9: ReqSetExp
	(*ReqGetExp)(nil),                // 10: ReqGetExp
	(*ReqSetGainMode)(nil),           // 11: ReqSetGainMode
	(*ReqGetGainMode)(nil),           // 12: ReqGetGainMode
	(*ReqSetGain)(nil),               // 13: ReqSetGain
	(*ReqGetGain)(nil),               // 14: ReqGetGain
	(*ReqSetBrightness)(nil),         // 15: ReqSetBrightness
	(*ReqGetBrightness)(nil),         // 16: ReqGetBrightness
	(*ReqSetContrast)(nil),           // 17: ReqSetContrast
	(*ReqGetContrast)(nil),           // 18: ReqGetContrast
	(*ReqSetHue)(nil),                // 19: ReqSetHue
	(*ReqGetHue)(nil),                // 20: ReqGetHue
	(*ReqSetSaturation)(nil),         // 21: ReqSetSaturation
	(*ReqGetSaturation)(nil),         // 22: ReqGetSaturation
	(*ReqSetSharpness)(nil),          // 23: ReqSetSharpness
	(*ReqGetSharpness)(nil),          // 24: ReqGetSharpness
	(*ReqSetWBMode)(nil),             // 25: ReqSetWBMode
	(*ReqGetWBMode)(nil),             // 26: ReqGetWBMode
	(*ReqSetWBSence)(nil),            // 27: ReqSetWBSence
	(*ReqGetWBSence)(nil),            // 28: ReqGetWBSence
	(*ReqSetWBCT)(nil),               // 29: ReqSetWBCT
	(*ReqGetWBCT)(nil),               // 30: ReqGetWBCT
	(*ReqSetIrCut)(nil),              // 31: ReqSetIrCut
	(*ReqGetIrcut)(nil),              // 32: ReqGetIrcut
	(*ReqStartTimeLapse)(nil),        // 33: ReqStartTimeLapse
	(*ReqStopTimeLapse)(nil),         // 34: ReqStopTimeLapse
	(*ReqSetAllParams)(nil),          // 35: ReqSetAllParams
	(*ReqGetAllParams)(nil),          // 36: ReqGetAllParams
	(*ResGetAllParams)(nil),          // 37: ResGetAllParams
	(*ReqSetFeatureParams)(nil),      // 38: ReqSetFeatureParams
	(*ReqGetAllFeatureParams)(nil),   // 39: ReqGetAllFeatureParams
	(*ResGetAllFeatureParams)(nil),   // 40: ResGetAllFeatureParams
	(*ReqGetSystemWorkingState)(nil), // 41: ReqGetSystemWorkingState
	(*ReqSetJpgQuality)(nil),         // 42: ReqSetJpgQuality
	(*ReqGetJpgQuality)(nil),         // 43: ReqGetJpgQuality
	(*CommonParam)(nil),              // 44: CommonParam
}
var file_camera_proto_depIdxs = []int32{
	44, // 0: ResGetAllParams.all_params:type_name -> CommonParam
	44, // 1: ReqSetFeatureParams.param:type_name -> CommonParam
	44, // 2: ResGetAllFeatureParams.all_feature_params:type_name -> CommonParam
	3,  // [3:3] is the sub-list for method output_type
	3,  // [3:3] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_camera_proto_init() }
func file_camera_proto_init() {
	if File_camera_proto != nil {
		return
	}
	file_base_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_camera_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqOpenCamera); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_camera_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqCloseCamera); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_camera_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqPhoto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_camera_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqBurstPhoto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_camera_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqStopBurstPhoto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_camera_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqStartRecord); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_camera_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqStopRecord); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_camera_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqSetExpMode); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_camera_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqGetExpMode); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_camera_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqSetExp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_camera_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqGetExp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_camera_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqSetGainMode); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_camera_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqGetGainMode); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_camera_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqSetGain); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_camera_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqGetGain); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_camera_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqSetBrightness); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_camera_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqGetBrightness); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_camera_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqSetContrast); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_camera_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqGetContrast); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_camera_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqSetHue); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_camera_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqGetHue); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_camera_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqSetSaturation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_camera_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqGetSaturation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_camera_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqSetSharpness); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_camera_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqGetSharpness); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_camera_proto_msgTypes[25].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqSetWBMode); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_camera_proto_msgTypes[26].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqGetWBMode); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_camera_proto_msgTypes[27].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqSetWBSence); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_camera_proto_msgTypes[28].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqGetWBSence); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_camera_proto_msgTypes[29].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqSetWBCT); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_camera_proto_msgTypes[30].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqGetWBCT); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_camera_proto_msgTypes[31].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqSetIrCut); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_camera_proto_msgTypes[32].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqGetIrcut); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_camera_proto_msgTypes[33].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqStartTimeLapse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_camera_proto_msgTypes[34].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqStopTimeLapse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_camera_proto_msgTypes[35].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqSetAllParams); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_camera_proto_msgTypes[36].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqGetAllParams); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_camera_proto_msgTypes[37].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResGetAllParams); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_camera_proto_msgTypes[38].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqSetFeatureParams); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_camera_proto_msgTypes[39].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqGetAllFeatureParams); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_camera_proto_msgTypes[40].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResGetAllFeatureParams); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_camera_proto_msgTypes[41].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqGetSystemWorkingState); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_camera_proto_msgTypes[42].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqSetJpgQuality); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_camera_proto_msgTypes[43].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqGetJpgQuality); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_camera_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   44,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_camera_proto_goTypes,
		DependencyIndexes: file_camera_proto_depIdxs,
		MessageInfos:      file_camera_proto_msgTypes,
	}.Build()
	File_camera_proto = out.File
	file_camera_proto_rawDesc = nil
	file_camera_proto_goTypes = nil
	file_camera_proto_depIdxs = nil
}
