// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v4.25.2
// source: focus.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 手动单次对焦
type ReqManualSingleStepFocus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Direction uint32 `protobuf:"varint,1,opt,name=direction,proto3" json:"direction,omitempty"`
}

func (x *ReqManualSingleStepFocus) Reset() {
	*x = ReqManualSingleStepFocus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_focus_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqManualSingleStepFocus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqManualSingleStepFocus) ProtoMessage() {}

func (x *ReqManualSingleStepFocus) ProtoReflect() protoreflect.Message {
	mi := &file_focus_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqManualSingleStepFocus.ProtoReflect.Descriptor instead.
func (*ReqManualSingleStepFocus) Descriptor() ([]byte, []int) {
	return file_focus_proto_rawDescGZIP(), []int{0}
}

func (x *ReqManualSingleStepFocus) GetDirection() uint32 {
	if x != nil {
		return x.Direction
	}
	return 0
}

// 手动连续对焦
type ReqManualContinuFocus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Direction uint32 `protobuf:"varint,1,opt,name=direction,proto3" json:"direction,omitempty"`
}

func (x *ReqManualContinuFocus) Reset() {
	*x = ReqManualContinuFocus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_focus_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqManualContinuFocus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqManualContinuFocus) ProtoMessage() {}

func (x *ReqManualContinuFocus) ProtoReflect() protoreflect.Message {
	mi := &file_focus_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqManualContinuFocus.ProtoReflect.Descriptor instead.
func (*ReqManualContinuFocus) Descriptor() ([]byte, []int) {
	return file_focus_proto_rawDescGZIP(), []int{1}
}

func (x *ReqManualContinuFocus) GetDirection() uint32 {
	if x != nil {
		return x.Direction
	}
	return 0
}

// 停止手动连续对焦
type ReqStopManualContinuFocus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ReqStopManualContinuFocus) Reset() {
	*x = ReqStopManualContinuFocus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_focus_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqStopManualContinuFocus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqStopManualContinuFocus) ProtoMessage() {}

func (x *ReqStopManualContinuFocus) ProtoReflect() protoreflect.Message {
	mi := &file_focus_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqStopManualContinuFocus.ProtoReflect.Descriptor instead.
func (*ReqStopManualContinuFocus) Descriptor() ([]byte, []int) {
	return file_focus_proto_rawDescGZIP(), []int{2}
}

// 普通模式自动对焦
type ReqNormalAutoFocus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mode    uint32 `protobuf:"varint,1,opt,name=mode,proto3" json:"mode,omitempty"`
	CenterX uint32 `protobuf:"varint,2,opt,name=center_x,json=centerX,proto3" json:"center_x,omitempty"`
	CenterY uint32 `protobuf:"varint,3,opt,name=center_y,json=centerY,proto3" json:"center_y,omitempty"`
}

func (x *ReqNormalAutoFocus) Reset() {
	*x = ReqNormalAutoFocus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_focus_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqNormalAutoFocus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqNormalAutoFocus) ProtoMessage() {}

func (x *ReqNormalAutoFocus) ProtoReflect() protoreflect.Message {
	mi := &file_focus_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqNormalAutoFocus.ProtoReflect.Descriptor instead.
func (*ReqNormalAutoFocus) Descriptor() ([]byte, []int) {
	return file_focus_proto_rawDescGZIP(), []int{3}
}

func (x *ReqNormalAutoFocus) GetMode() uint32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

func (x *ReqNormalAutoFocus) GetCenterX() uint32 {
	if x != nil {
		return x.CenterX
	}
	return 0
}

func (x *ReqNormalAutoFocus) GetCenterY() uint32 {
	if x != nil {
		return x.CenterY
	}
	return 0
}

// 开始天文自动对焦
type ReqAstroAutoFocus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mode uint32 `protobuf:"varint,1,opt,name=mode,proto3" json:"mode,omitempty"`
}

func (x *ReqAstroAutoFocus) Reset() {
	*x = ReqAstroAutoFocus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_focus_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqAstroAutoFocus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqAstroAutoFocus) ProtoMessage() {}

func (x *ReqAstroAutoFocus) ProtoReflect() protoreflect.Message {
	mi := &file_focus_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqAstroAutoFocus.ProtoReflect.Descriptor instead.
func (*ReqAstroAutoFocus) Descriptor() ([]byte, []int) {
	return file_focus_proto_rawDescGZIP(), []int{4}
}

func (x *ReqAstroAutoFocus) GetMode() uint32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

// 停止天文自动对焦
type ReqStopAstroAutoFocus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ReqStopAstroAutoFocus) Reset() {
	*x = ReqStopAstroAutoFocus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_focus_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqStopAstroAutoFocus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqStopAstroAutoFocus) ProtoMessage() {}

func (x *ReqStopAstroAutoFocus) ProtoReflect() protoreflect.Message {
	mi := &file_focus_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqStopAstroAutoFocus.ProtoReflect.Descriptor instead.
func (*ReqStopAstroAutoFocus) Descriptor() ([]byte, []int) {
	return file_focus_proto_rawDescGZIP(), []int{5}
}

var File_focus_proto protoreflect.FileDescriptor

var file_focus_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x66, 0x6f, 0x63, 0x75, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x38, 0x0a,
	0x18, 0x52, 0x65, 0x71, 0x4d, 0x61, 0x6e, 0x75, 0x61, 0x6c, 0x53, 0x69, 0x6e, 0x67, 0x6c, 0x65,
	0x53, 0x74, 0x65, 0x70, 0x46, 0x6f, 0x63, 0x75, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x64, 0x69, 0x72,
	0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x64, 0x69,
	0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x35, 0x0a, 0x15, 0x52, 0x65, 0x71, 0x4d, 0x61,
	0x6e, 0x75, 0x61, 0x6c, 0x43, 0x6f, 0x6e, 0x74, 0x69, 0x6e, 0x75, 0x46, 0x6f, 0x63, 0x75, 0x73,
	0x12, 0x1c, 0x0a, 0x09, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x09, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x1b,
	0x0a, 0x19, 0x52, 0x65, 0x71, 0x53, 0x74, 0x6f, 0x70, 0x4d, 0x61, 0x6e, 0x75, 0x61, 0x6c, 0x43,
	0x6f, 0x6e, 0x74, 0x69, 0x6e, 0x75, 0x46, 0x6f, 0x63, 0x75, 0x73, 0x22, 0x5e, 0x0a, 0x12, 0x52,
	0x65, 0x71, 0x4e, 0x6f, 0x72, 0x6d, 0x61, 0x6c, 0x41, 0x75, 0x74, 0x6f, 0x46, 0x6f, 0x63, 0x75,
	0x73, 0x12, 0x12, 0x0a, 0x04, 0x6d, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x04, 0x6d, 0x6f, 0x64, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x63, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x5f,
	0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x63, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x58,
	0x12, 0x19, 0x0a, 0x08, 0x63, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x5f, 0x79, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x07, 0x63, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x59, 0x22, 0x27, 0x0a, 0x11, 0x52,
	0x65, 0x71, 0x41, 0x73, 0x74, 0x72, 0x6f, 0x41, 0x75, 0x74, 0x6f, 0x46, 0x6f, 0x63, 0x75, 0x73,
	0x12, 0x12, 0x0a, 0x04, 0x6d, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04,
	0x6d, 0x6f, 0x64, 0x65, 0x22, 0x17, 0x0a, 0x15, 0x52, 0x65, 0x71, 0x53, 0x74, 0x6f, 0x70, 0x41,
	0x73, 0x74, 0x72, 0x6f, 0x41, 0x75, 0x74, 0x6f, 0x46, 0x6f, 0x63, 0x75, 0x73, 0x42, 0x1b, 0x5a,
	0x19, 0x76, 0x70, 0x72, 0x65, 0x6e, 0x6e, 0x65, 0x72, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x64, 0x77,
	0x61, 0x72, 0x66, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_focus_proto_rawDescOnce sync.Once
	file_focus_proto_rawDescData = file_focus_proto_rawDesc
)

func file_focus_proto_rawDescGZIP() []byte {
	file_focus_proto_rawDescOnce.Do(func() {
		file_focus_proto_rawDescData = protoimpl.X.CompressGZIP(file_focus_proto_rawDescData)
	})
	return file_focus_proto_rawDescData
}

var file_focus_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_focus_proto_goTypes = []interface{}{
	(*ReqManualSingleStepFocus)(nil),  // 0: ReqManualSingleStepFocus
	(*ReqManualContinuFocus)(nil),     // 1: ReqManualContinuFocus
	(*ReqStopManualContinuFocus)(nil), // 2: ReqStopManualContinuFocus
	(*ReqNormalAutoFocus)(nil),        // 3: ReqNormalAutoFocus
	(*ReqAstroAutoFocus)(nil),         // 4: ReqAstroAutoFocus
	(*ReqStopAstroAutoFocus)(nil),     // 5: ReqStopAstroAutoFocus
}
var file_focus_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_focus_proto_init() }
func file_focus_proto_init() {
	if File_focus_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_focus_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqManualSingleStepFocus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_focus_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqManualContinuFocus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_focus_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqStopManualContinuFocus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_focus_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqNormalAutoFocus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_focus_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqAstroAutoFocus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_focus_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqStopAstroAutoFocus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_focus_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_focus_proto_goTypes,
		DependencyIndexes: file_focus_proto_depIdxs,
		MessageInfos:      file_focus_proto_msgTypes,
	}.Build()
	File_focus_proto = out.File
	file_focus_proto_rawDesc = nil
	file_focus_proto_goTypes = nil
	file_focus_proto_depIdxs = nil
}
