// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v4.25.2
// source: motor_control.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReqMotorServiceJoystick struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VectorAngle  float64 `protobuf:"fixed64,1,opt,name=vector_angle,json=vectorAngle,proto3" json:"vector_angle,omitempty"`
	VectorLength float64 `protobuf:"fixed64,2,opt,name=vector_length,json=vectorLength,proto3" json:"vector_length,omitempty"`
	Speed        float64 `protobuf:"fixed64,3,opt,name=speed,proto3" json:"speed,omitempty"`
}

func (x *ReqMotorServiceJoystick) Reset() {
	*x = ReqMotorServiceJoystick{}
	if protoimpl.UnsafeEnabled {
		mi := &file_motor_control_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqMotorServiceJoystick) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqMotorServiceJoystick) ProtoMessage() {}

func (x *ReqMotorServiceJoystick) ProtoReflect() protoreflect.Message {
	mi := &file_motor_control_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqMotorServiceJoystick.ProtoReflect.Descriptor instead.
func (*ReqMotorServiceJoystick) Descriptor() ([]byte, []int) {
	return file_motor_control_proto_rawDescGZIP(), []int{0}
}

func (x *ReqMotorServiceJoystick) GetVectorAngle() float64 {
	if x != nil {
		return x.VectorAngle
	}
	return 0
}

func (x *ReqMotorServiceJoystick) GetVectorLength() float64 {
	if x != nil {
		return x.VectorLength
	}
	return 0
}

func (x *ReqMotorServiceJoystick) GetSpeed() float64 {
	if x != nil {
		return x.Speed
	}
	return 0
}

type ReqMotorServiceJoystickFixedAngle struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VectorAngle  float64 `protobuf:"fixed64,1,opt,name=vector_angle,json=vectorAngle,proto3" json:"vector_angle,omitempty"`
	VectorLength float64 `protobuf:"fixed64,2,opt,name=vector_length,json=vectorLength,proto3" json:"vector_length,omitempty"`
	Speed        float64 `protobuf:"fixed64,3,opt,name=speed,proto3" json:"speed,omitempty"`
}

func (x *ReqMotorServiceJoystickFixedAngle) Reset() {
	*x = ReqMotorServiceJoystickFixedAngle{}
	if protoimpl.UnsafeEnabled {
		mi := &file_motor_control_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqMotorServiceJoystickFixedAngle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqMotorServiceJoystickFixedAngle) ProtoMessage() {}

func (x *ReqMotorServiceJoystickFixedAngle) ProtoReflect() protoreflect.Message {
	mi := &file_motor_control_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqMotorServiceJoystickFixedAngle.ProtoReflect.Descriptor instead.
func (*ReqMotorServiceJoystickFixedAngle) Descriptor() ([]byte, []int) {
	return file_motor_control_proto_rawDescGZIP(), []int{1}
}

func (x *ReqMotorServiceJoystickFixedAngle) GetVectorAngle() float64 {
	if x != nil {
		return x.VectorAngle
	}
	return 0
}

func (x *ReqMotorServiceJoystickFixedAngle) GetVectorLength() float64 {
	if x != nil {
		return x.VectorLength
	}
	return 0
}

func (x *ReqMotorServiceJoystickFixedAngle) GetSpeed() float64 {
	if x != nil {
		return x.Speed
	}
	return 0
}

type ReqMotorServiceJoystickStop struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ReqMotorServiceJoystickStop) Reset() {
	*x = ReqMotorServiceJoystickStop{}
	if protoimpl.UnsafeEnabled {
		mi := &file_motor_control_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqMotorServiceJoystickStop) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqMotorServiceJoystickStop) ProtoMessage() {}

func (x *ReqMotorServiceJoystickStop) ProtoReflect() protoreflect.Message {
	mi := &file_motor_control_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqMotorServiceJoystickStop.ProtoReflect.Descriptor instead.
func (*ReqMotorServiceJoystickStop) Descriptor() ([]byte, []int) {
	return file_motor_control_proto_rawDescGZIP(), []int{2}
}

type ReqMotorRun struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id              int32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Speed           float64 `protobuf:"fixed64,2,opt,name=speed,proto3" json:"speed,omitempty"`
	Direction       bool    `protobuf:"varint,3,opt,name=direction,proto3" json:"direction,omitempty"`
	SpeedRamping    int32   `protobuf:"varint,4,opt,name=speed_ramping,json=speedRamping,proto3" json:"speed_ramping,omitempty"`
	ResolutionLevel int32   `protobuf:"varint,5,opt,name=resolution_level,json=resolutionLevel,proto3" json:"resolution_level,omitempty"`
}

func (x *ReqMotorRun) Reset() {
	*x = ReqMotorRun{}
	if protoimpl.UnsafeEnabled {
		mi := &file_motor_control_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqMotorRun) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqMotorRun) ProtoMessage() {}

func (x *ReqMotorRun) ProtoReflect() protoreflect.Message {
	mi := &file_motor_control_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqMotorRun.ProtoReflect.Descriptor instead.
func (*ReqMotorRun) Descriptor() ([]byte, []int) {
	return file_motor_control_proto_rawDescGZIP(), []int{3}
}

func (x *ReqMotorRun) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ReqMotorRun) GetSpeed() float64 {
	if x != nil {
		return x.Speed
	}
	return 0
}

func (x *ReqMotorRun) GetDirection() bool {
	if x != nil {
		return x.Direction
	}
	return false
}

func (x *ReqMotorRun) GetSpeedRamping() int32 {
	if x != nil {
		return x.SpeedRamping
	}
	return 0
}

func (x *ReqMotorRun) GetResolutionLevel() int32 {
	if x != nil {
		return x.ResolutionLevel
	}
	return 0
}

type ReqMotorRunTo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id              int32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	EndPosition     float64 `protobuf:"fixed64,2,opt,name=end_position,json=endPosition,proto3" json:"end_position,omitempty"`
	Speed           float64 `protobuf:"fixed64,3,opt,name=speed,proto3" json:"speed,omitempty"`
	SpeedRamping    int32   `protobuf:"varint,4,opt,name=speed_ramping,json=speedRamping,proto3" json:"speed_ramping,omitempty"`
	ResolutionLevel int32   `protobuf:"varint,5,opt,name=resolution_level,json=resolutionLevel,proto3" json:"resolution_level,omitempty"`
}

func (x *ReqMotorRunTo) Reset() {
	*x = ReqMotorRunTo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_motor_control_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqMotorRunTo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqMotorRunTo) ProtoMessage() {}

func (x *ReqMotorRunTo) ProtoReflect() protoreflect.Message {
	mi := &file_motor_control_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqMotorRunTo.ProtoReflect.Descriptor instead.
func (*ReqMotorRunTo) Descriptor() ([]byte, []int) {
	return file_motor_control_proto_rawDescGZIP(), []int{4}
}

func (x *ReqMotorRunTo) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ReqMotorRunTo) GetEndPosition() float64 {
	if x != nil {
		return x.EndPosition
	}
	return 0
}

func (x *ReqMotorRunTo) GetSpeed() float64 {
	if x != nil {
		return x.Speed
	}
	return 0
}

func (x *ReqMotorRunTo) GetSpeedRamping() int32 {
	if x != nil {
		return x.SpeedRamping
	}
	return 0
}

func (x *ReqMotorRunTo) GetResolutionLevel() int32 {
	if x != nil {
		return x.ResolutionLevel
	}
	return 0
}

type ReqMotorStop struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *ReqMotorStop) Reset() {
	*x = ReqMotorStop{}
	if protoimpl.UnsafeEnabled {
		mi := &file_motor_control_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqMotorStop) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqMotorStop) ProtoMessage() {}

func (x *ReqMotorStop) ProtoReflect() protoreflect.Message {
	mi := &file_motor_control_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqMotorStop.ProtoReflect.Descriptor instead.
func (*ReqMotorStop) Descriptor() ([]byte, []int) {
	return file_motor_control_proto_rawDescGZIP(), []int{5}
}

func (x *ReqMotorStop) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ReqMotorReset struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Direction bool  `protobuf:"varint,2,opt,name=direction,proto3" json:"direction,omitempty"`
}

func (x *ReqMotorReset) Reset() {
	*x = ReqMotorReset{}
	if protoimpl.UnsafeEnabled {
		mi := &file_motor_control_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqMotorReset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqMotorReset) ProtoMessage() {}

func (x *ReqMotorReset) ProtoReflect() protoreflect.Message {
	mi := &file_motor_control_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqMotorReset.ProtoReflect.Descriptor instead.
func (*ReqMotorReset) Descriptor() ([]byte, []int) {
	return file_motor_control_proto_rawDescGZIP(), []int{6}
}

func (x *ReqMotorReset) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ReqMotorReset) GetDirection() bool {
	if x != nil {
		return x.Direction
	}
	return false
}

type ReqMotorChangeSpeed struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    int32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Speed float64 `protobuf:"fixed64,2,opt,name=speed,proto3" json:"speed,omitempty"`
}

func (x *ReqMotorChangeSpeed) Reset() {
	*x = ReqMotorChangeSpeed{}
	if protoimpl.UnsafeEnabled {
		mi := &file_motor_control_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqMotorChangeSpeed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqMotorChangeSpeed) ProtoMessage() {}

func (x *ReqMotorChangeSpeed) ProtoReflect() protoreflect.Message {
	mi := &file_motor_control_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqMotorChangeSpeed.ProtoReflect.Descriptor instead.
func (*ReqMotorChangeSpeed) Descriptor() ([]byte, []int) {
	return file_motor_control_proto_rawDescGZIP(), []int{7}
}

func (x *ReqMotorChangeSpeed) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ReqMotorChangeSpeed) GetSpeed() float64 {
	if x != nil {
		return x.Speed
	}
	return 0
}

type ReqMotorChangeDirection struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Direction bool  `protobuf:"varint,2,opt,name=direction,proto3" json:"direction,omitempty"`
}

func (x *ReqMotorChangeDirection) Reset() {
	*x = ReqMotorChangeDirection{}
	if protoimpl.UnsafeEnabled {
		mi := &file_motor_control_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqMotorChangeDirection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqMotorChangeDirection) ProtoMessage() {}

func (x *ReqMotorChangeDirection) ProtoReflect() protoreflect.Message {
	mi := &file_motor_control_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqMotorChangeDirection.ProtoReflect.Descriptor instead.
func (*ReqMotorChangeDirection) Descriptor() ([]byte, []int) {
	return file_motor_control_proto_rawDescGZIP(), []int{8}
}

func (x *ReqMotorChangeDirection) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ReqMotorChangeDirection) GetDirection() bool {
	if x != nil {
		return x.Direction
	}
	return false
}

type ResMotor struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Code int32 `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
}

func (x *ResMotor) Reset() {
	*x = ResMotor{}
	if protoimpl.UnsafeEnabled {
		mi := &file_motor_control_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResMotor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResMotor) ProtoMessage() {}

func (x *ResMotor) ProtoReflect() protoreflect.Message {
	mi := &file_motor_control_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResMotor.ProtoReflect.Descriptor instead.
func (*ResMotor) Descriptor() ([]byte, []int) {
	return file_motor_control_proto_rawDescGZIP(), []int{9}
}

func (x *ResMotor) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ResMotor) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

type ResMotorPosition struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       int32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Code     int32   `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	Position float64 `protobuf:"fixed64,3,opt,name=position,proto3" json:"position,omitempty"`
}

func (x *ResMotorPosition) Reset() {
	*x = ResMotorPosition{}
	if protoimpl.UnsafeEnabled {
		mi := &file_motor_control_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResMotorPosition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResMotorPosition) ProtoMessage() {}

func (x *ResMotorPosition) ProtoReflect() protoreflect.Message {
	mi := &file_motor_control_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResMotorPosition.ProtoReflect.Descriptor instead.
func (*ResMotorPosition) Descriptor() ([]byte, []int) {
	return file_motor_control_proto_rawDescGZIP(), []int{10}
}

func (x *ResMotorPosition) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ResMotorPosition) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ResMotorPosition) GetPosition() float64 {
	if x != nil {
		return x.Position
	}
	return 0
}

// 双摄联动
type ReqDualCameraLinkage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X int32 `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y int32 `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
}

func (x *ReqDualCameraLinkage) Reset() {
	*x = ReqDualCameraLinkage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_motor_control_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqDualCameraLinkage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqDualCameraLinkage) ProtoMessage() {}

func (x *ReqDualCameraLinkage) ProtoReflect() protoreflect.Message {
	mi := &file_motor_control_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqDualCameraLinkage.ProtoReflect.Descriptor instead.
func (*ReqDualCameraLinkage) Descriptor() ([]byte, []int) {
	return file_motor_control_proto_rawDescGZIP(), []int{11}
}

func (x *ReqDualCameraLinkage) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *ReqDualCameraLinkage) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

var File_motor_control_proto protoreflect.FileDescriptor

var file_motor_control_proto_rawDesc = []byte{
	0x0a, 0x13, 0x6d, 0x6f, 0x74, 0x6f, 0x72, 0x5f, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x77, 0x0a, 0x17, 0x52, 0x65, 0x71, 0x4d, 0x6f, 0x74, 0x6f,
	0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x4a, 0x6f, 0x79, 0x73, 0x74, 0x69, 0x63, 0x6b,
	0x12, 0x21, 0x0a, 0x0c, 0x76, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x5f, 0x61, 0x6e, 0x67, 0x6c, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0b, 0x76, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x41, 0x6e,
	0x67, 0x6c, 0x65, 0x12, 0x23, 0x0a, 0x0d, 0x76, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x5f, 0x6c, 0x65,
	0x6e, 0x67, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0c, 0x76, 0x65, 0x63, 0x74,
	0x6f, 0x72, 0x4c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x70, 0x65, 0x65,
	0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x73, 0x70, 0x65, 0x65, 0x64, 0x22, 0x81,
	0x01, 0x0a, 0x21, 0x52, 0x65, 0x71, 0x4d, 0x6f, 0x74, 0x6f, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x4a, 0x6f, 0x79, 0x73, 0x74, 0x69, 0x63, 0x6b, 0x46, 0x69, 0x78, 0x65, 0x64, 0x41,
	0x6e, 0x67, 0x6c, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x76, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x5f, 0x61,
	0x6e, 0x67, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0b, 0x76, 0x65, 0x63, 0x74,
	0x6f, 0x72, 0x41, 0x6e, 0x67, 0x6c, 0x65, 0x12, 0x23, 0x0a, 0x0d, 0x76, 0x65, 0x63, 0x74, 0x6f,
	0x72, 0x5f, 0x6c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0c,
	0x76, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x4c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x12, 0x14, 0x0a, 0x05,
	0x73, 0x70, 0x65, 0x65, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x73, 0x70, 0x65,
	0x65, 0x64, 0x22, 0x1d, 0x0a, 0x1b, 0x52, 0x65, 0x71, 0x4d, 0x6f, 0x74, 0x6f, 0x72, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x4a, 0x6f, 0x79, 0x73, 0x74, 0x69, 0x63, 0x6b, 0x53, 0x74, 0x6f,
	0x70, 0x22, 0xa1, 0x01, 0x0a, 0x0b, 0x52, 0x65, 0x71, 0x4d, 0x6f, 0x74, 0x6f, 0x72, 0x52, 0x75,
	0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x70, 0x65, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01,
	0x52, 0x05, 0x73, 0x70, 0x65, 0x65, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x64, 0x69, 0x72, 0x65, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x64, 0x69, 0x72, 0x65,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x23, 0x0a, 0x0d, 0x73, 0x70, 0x65, 0x65, 0x64, 0x5f, 0x72,
	0x61, 0x6d, 0x70, 0x69, 0x6e, 0x67, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x73, 0x70,
	0x65, 0x65, 0x64, 0x52, 0x61, 0x6d, 0x70, 0x69, 0x6e, 0x67, 0x12, 0x29, 0x0a, 0x10, 0x72, 0x65,
	0x73, 0x6f, 0x6c, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x0f, 0x72, 0x65, 0x73, 0x6f, 0x6c, 0x75, 0x74, 0x69, 0x6f, 0x6e,
	0x4c, 0x65, 0x76, 0x65, 0x6c, 0x22, 0xa8, 0x01, 0x0a, 0x0d, 0x52, 0x65, 0x71, 0x4d, 0x6f, 0x74,
	0x6f, 0x72, 0x52, 0x75, 0x6e, 0x54, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x65, 0x6e, 0x64, 0x5f, 0x70,
	0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0b, 0x65,
	0x6e, 0x64, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x70,
	0x65, 0x65, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x73, 0x70, 0x65, 0x65, 0x64,
	0x12, 0x23, 0x0a, 0x0d, 0x73, 0x70, 0x65, 0x65, 0x64, 0x5f, 0x72, 0x61, 0x6d, 0x70, 0x69, 0x6e,
	0x67, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x73, 0x70, 0x65, 0x65, 0x64, 0x52, 0x61,
	0x6d, 0x70, 0x69, 0x6e, 0x67, 0x12, 0x29, 0x0a, 0x10, 0x72, 0x65, 0x73, 0x6f, 0x6c, 0x75, 0x74,
	0x69, 0x6f, 0x6e, 0x5f, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x0f, 0x72, 0x65, 0x73, 0x6f, 0x6c, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x4c, 0x65, 0x76, 0x65, 0x6c,
	0x22, 0x1e, 0x0a, 0x0c, 0x52, 0x65, 0x71, 0x4d, 0x6f, 0x74, 0x6f, 0x72, 0x53, 0x74, 0x6f, 0x70,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64,
	0x22, 0x3d, 0x0a, 0x0d, 0x52, 0x65, 0x71, 0x4d, 0x6f, 0x74, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x65,
	0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x1c, 0x0a, 0x09, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x22,
	0x3b, 0x0a, 0x13, 0x52, 0x65, 0x71, 0x4d, 0x6f, 0x74, 0x6f, 0x72, 0x43, 0x68, 0x61, 0x6e, 0x67,
	0x65, 0x53, 0x70, 0x65, 0x65, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x70, 0x65, 0x65, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x73, 0x70, 0x65, 0x65, 0x64, 0x22, 0x47, 0x0a, 0x17,
	0x52, 0x65, 0x71, 0x4d, 0x6f, 0x74, 0x6f, 0x72, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x44, 0x69,
	0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x64, 0x69, 0x72, 0x65, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x64, 0x69, 0x72, 0x65,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x2e, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x4d, 0x6f, 0x74, 0x6f,
	0x72, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x04, 0x63, 0x6f, 0x64, 0x65, 0x22, 0x52, 0x0a, 0x10, 0x52, 0x65, 0x73, 0x4d, 0x6f, 0x74, 0x6f,
	0x72, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x1a, 0x0a,
	0x08, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52,
	0x08, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x32, 0x0a, 0x14, 0x52, 0x65, 0x71,
	0x44, 0x75, 0x61, 0x6c, 0x43, 0x61, 0x6d, 0x65, 0x72, 0x61, 0x4c, 0x69, 0x6e, 0x6b, 0x61, 0x67,
	0x65, 0x12, 0x0c, 0x0a, 0x01, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x01, 0x78, 0x12,
	0x0c, 0x0a, 0x01, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x01, 0x79, 0x42, 0x1b, 0x5a,
	0x19, 0x76, 0x70, 0x72, 0x65, 0x6e, 0x6e, 0x65, 0x72, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x64, 0x77,
	0x61, 0x72, 0x66, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_motor_control_proto_rawDescOnce sync.Once
	file_motor_control_proto_rawDescData = file_motor_control_proto_rawDesc
)

func file_motor_control_proto_rawDescGZIP() []byte {
	file_motor_control_proto_rawDescOnce.Do(func() {
		file_motor_control_proto_rawDescData = protoimpl.X.CompressGZIP(file_motor_control_proto_rawDescData)
	})
	return file_motor_control_proto_rawDescData
}

var file_motor_control_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_motor_control_proto_goTypes = []interface{}{
	(*ReqMotorServiceJoystick)(nil),           // 0: ReqMotorServiceJoystick
	(*ReqMotorServiceJoystickFixedAngle)(nil), // 1: ReqMotorServiceJoystickFixedAngle
	(*ReqMotorServiceJoystickStop)(nil),       // 2: ReqMotorServiceJoystickStop
	(*ReqMotorRun)(nil),                       // 3: ReqMotorRun
	(*ReqMotorRunTo)(nil),                     // 4: ReqMotorRunTo
	(*ReqMotorStop)(nil),                      // 5: ReqMotorStop
	(*ReqMotorReset)(nil),                     // 6: ReqMotorReset
	(*ReqMotorChangeSpeed)(nil),               // 7: ReqMotorChangeSpeed
	(*ReqMotorChangeDirection)(nil),           // 8: ReqMotorChangeDirection
	(*ResMotor)(nil),                          // 9: ResMotor
	(*ResMotorPosition)(nil),                  // 10: ResMotorPosition
	(*ReqDualCameraLinkage)(nil),              // 11: ReqDualCameraLinkage
}
var file_motor_control_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_motor_control_proto_init() }
func file_motor_control_proto_init() {
	if File_motor_control_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_motor_control_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqMotorServiceJoystick); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_motor_control_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqMotorServiceJoystickFixedAngle); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_motor_control_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqMotorServiceJoystickStop); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_motor_control_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqMotorRun); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_motor_control_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqMotorRunTo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_motor_control_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqMotorStop); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_motor_control_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqMotorReset); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_motor_control_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqMotorChangeSpeed); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_motor_control_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqMotorChangeDirection); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_motor_control_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResMotor); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_motor_control_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResMotorPosition); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_motor_control_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqDualCameraLinkage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_motor_control_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_motor_control_proto_goTypes,
		DependencyIndexes: file_motor_control_proto_depIdxs,
		MessageInfos:      file_motor_control_proto_msgTypes,
	}.Build()
	File_motor_control_proto = out.File
	file_motor_control_proto_rawDesc = nil
	file_motor_control_proto_goTypes = nil
	file_motor_control_proto_depIdxs = nil
}
