// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v4.25.2
// source: notify.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type State int32

const (
	State_STATE_IDLE                State = 0 // Idle state
	State_STATE_RUNNING             State = 1 // Running
	State_STATE_STOPPING            State = 2 // Is stopping
	State_STATE_STOPPED             State = 3 // Has stopped
	State_STATE_SUCCESS             State = 4 // Success
	State_STATE_FAILED              State = 5 // Failure
	State_STATE_ASTRO_PLATE_SOLVING State = 6 // Astronomy is Plating Solving
)

// Enum value maps for State.
var (
	State_name = map[int32]string{
		0: "STATE_IDLE",
		1: "STATE_RUNNING",
		2: "STATE_STOPPING",
		3: "STATE_STOPPED",
		4: "STATE_SUCCESS",
		5: "STATE_FAILED",
		6: "STATE_ASTRO_PLATE_SOLVING",
	}
	State_value = map[string]int32{
		"STATE_IDLE":                0,
		"STATE_RUNNING":             1,
		"STATE_STOPPING":            2,
		"STATE_STOPPED":             3,
		"STATE_SUCCESS":             4,
		"STATE_FAILED":              5,
		"STATE_ASTRO_PLATE_SOLVING": 6,
	}
)

func (x State) Enum() *State {
	p := new(State)
	*p = x
	return p
}

func (x State) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (State) Descriptor() protoreflect.EnumDescriptor {
	return file_notify_proto_enumTypes[0].Descriptor()
}

func (State) Type() protoreflect.EnumType {
	return &file_notify_proto_enumTypes[0]
}

func (x State) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use State.Descriptor instead.
func (State) EnumDescriptor() ([]byte, []int) {
	return file_notify_proto_rawDescGZIP(), []int{0}
}

type OperationState int32

const (
	OperationState_OPERATION_STATE_IDLE     OperationState = 0
	OperationState_OPERATION_STATE_RUNNING  OperationState = 1
	OperationState_OPERATION_STATE_STOPPING OperationState = 2
	OperationState_OPERATION_STATE_STOPPED  OperationState = 3
)

// Enum value maps for OperationState.
var (
	OperationState_name = map[int32]string{
		0: "OPERATION_STATE_IDLE",
		1: "OPERATION_STATE_RUNNING",
		2: "OPERATION_STATE_STOPPING",
		3: "OPERATION_STATE_STOPPED",
	}
	OperationState_value = map[string]int32{
		"OPERATION_STATE_IDLE":     0,
		"OPERATION_STATE_RUNNING":  1,
		"OPERATION_STATE_STOPPING": 2,
		"OPERATION_STATE_STOPPED":  3,
	}
)

func (x OperationState) Enum() *OperationState {
	p := new(OperationState)
	*p = x
	return p
}

func (x OperationState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OperationState) Descriptor() protoreflect.EnumDescriptor {
	return file_notify_proto_enumTypes[1].Descriptor()
}

func (OperationState) Type() protoreflect.EnumType {
	return &file_notify_proto_enumTypes[1]
}

func (x OperationState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OperationState.Descriptor instead.
func (OperationState) EnumDescriptor() ([]byte, []int) {
	return file_notify_proto_rawDescGZIP(), []int{1}
}

type AstroState int32

const (
	AstroState_ASTRO_STATE_IDLE          AstroState = 0 // Idle state
	AstroState_ASTRO_STATE_RUNNING       AstroState = 1 // Running
	AstroState_ASTRO_STATE_STOPPING      AstroState = 2 // Is stopping
	AstroState_ASTRO_STATE_STOPPED       AstroState = 3 // Has stopped
	AstroState_ASTRO_STATE_PLATE_SOLVING AstroState = 4 // Astronomy is Plating Solving
)

// Enum value maps for AstroState.
var (
	AstroState_name = map[int32]string{
		0: "ASTRO_STATE_IDLE",
		1: "ASTRO_STATE_RUNNING",
		2: "ASTRO_STATE_STOPPING",
		3: "ASTRO_STATE_STOPPED",
		4: "ASTRO_STATE_PLATE_SOLVING",
	}
	AstroState_value = map[string]int32{
		"ASTRO_STATE_IDLE":          0,
		"ASTRO_STATE_RUNNING":       1,
		"ASTRO_STATE_STOPPING":      2,
		"ASTRO_STATE_STOPPED":       3,
		"ASTRO_STATE_PLATE_SOLVING": 4,
	}
)

func (x AstroState) Enum() *AstroState {
	p := new(AstroState)
	*p = x
	return p
}

func (x AstroState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AstroState) Descriptor() protoreflect.EnumDescriptor {
	return file_notify_proto_enumTypes[2].Descriptor()
}

func (AstroState) Type() protoreflect.EnumType {
	return &file_notify_proto_enumTypes[2]
}

func (x AstroState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AstroState.Descriptor instead.
func (AstroState) EnumDescriptor() ([]byte, []int) {
	return file_notify_proto_rawDescGZIP(), []int{2}
}

// 长焦广角预览画面匹配结果
type ResNotifyPictureMatching struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X      uint32  `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y      uint32  `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	Width  uint32  `protobuf:"varint,3,opt,name=width,proto3" json:"width,omitempty"`
	Height uint32  `protobuf:"varint,4,opt,name=height,proto3" json:"height,omitempty"`
	Value  float64 `protobuf:"fixed64,5,opt,name=value,proto3" json:"value,omitempty"`
	Code   int32   `protobuf:"varint,6,opt,name=code,proto3" json:"code,omitempty"`
}

func (x *ResNotifyPictureMatching) Reset() {
	*x = ResNotifyPictureMatching{}
	if protoimpl.UnsafeEnabled {
		mi := &file_notify_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResNotifyPictureMatching) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResNotifyPictureMatching) ProtoMessage() {}

func (x *ResNotifyPictureMatching) ProtoReflect() protoreflect.Message {
	mi := &file_notify_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResNotifyPictureMatching.ProtoReflect.Descriptor instead.
func (*ResNotifyPictureMatching) Descriptor() ([]byte, []int) {
	return file_notify_proto_rawDescGZIP(), []int{0}
}

func (x *ResNotifyPictureMatching) GetX() uint32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *ResNotifyPictureMatching) GetY() uint32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *ResNotifyPictureMatching) GetWidth() uint32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *ResNotifyPictureMatching) GetHeight() uint32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *ResNotifyPictureMatching) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *ResNotifyPictureMatching) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

// SD卡容量信息
type ResNotifySDcardInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AvailableSize uint32 `protobuf:"varint,1,opt,name=available_size,json=availableSize,proto3" json:"available_size,omitempty"`
	TotalSize     uint32 `protobuf:"varint,2,opt,name=total_size,json=totalSize,proto3" json:"total_size,omitempty"`
	Code          int32  `protobuf:"varint,3,opt,name=code,proto3" json:"code,omitempty"`
}

func (x *ResNotifySDcardInfo) Reset() {
	*x = ResNotifySDcardInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_notify_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResNotifySDcardInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResNotifySDcardInfo) ProtoMessage() {}

func (x *ResNotifySDcardInfo) ProtoReflect() protoreflect.Message {
	mi := &file_notify_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResNotifySDcardInfo.ProtoReflect.Descriptor instead.
func (*ResNotifySDcardInfo) Descriptor() ([]byte, []int) {
	return file_notify_proto_rawDescGZIP(), []int{1}
}

func (x *ResNotifySDcardInfo) GetAvailableSize() uint32 {
	if x != nil {
		return x.AvailableSize
	}
	return 0
}

func (x *ResNotifySDcardInfo) GetTotalSize() uint32 {
	if x != nil {
		return x.TotalSize
	}
	return 0
}

func (x *ResNotifySDcardInfo) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

// 录像时间显示
type ResNotifyRecordTime struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RecordTime int32 `protobuf:"varint,1,opt,name=record_time,json=recordTime,proto3" json:"record_time,omitempty"`
}

func (x *ResNotifyRecordTime) Reset() {
	*x = ResNotifyRecordTime{}
	if protoimpl.UnsafeEnabled {
		mi := &file_notify_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResNotifyRecordTime) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResNotifyRecordTime) ProtoMessage() {}

func (x *ResNotifyRecordTime) ProtoReflect() protoreflect.Message {
	mi := &file_notify_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResNotifyRecordTime.ProtoReflect.Descriptor instead.
func (*ResNotifyRecordTime) Descriptor() ([]byte, []int) {
	return file_notify_proto_rawDescGZIP(), []int{2}
}

func (x *ResNotifyRecordTime) GetRecordTime() int32 {
	if x != nil {
		return x.RecordTime
	}
	return 0
}

// 延时摄影时间显示
type ResNotifyTimeLapseOutTime struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Interval  int32 `protobuf:"varint,1,opt,name=interval,proto3" json:"interval,omitempty"`
	OutTime   int32 `protobuf:"varint,2,opt,name=out_time,json=outTime,proto3" json:"out_time,omitempty"`
	TotalTime int32 `protobuf:"varint,3,opt,name=total_time,json=totalTime,proto3" json:"total_time,omitempty"`
}

func (x *ResNotifyTimeLapseOutTime) Reset() {
	*x = ResNotifyTimeLapseOutTime{}
	if protoimpl.UnsafeEnabled {
		mi := &file_notify_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResNotifyTimeLapseOutTime) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResNotifyTimeLapseOutTime) ProtoMessage() {}

func (x *ResNotifyTimeLapseOutTime) ProtoReflect() protoreflect.Message {
	mi := &file_notify_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResNotifyTimeLapseOutTime.ProtoReflect.Descriptor instead.
func (*ResNotifyTimeLapseOutTime) Descriptor() ([]byte, []int) {
	return file_notify_proto_rawDescGZIP(), []int{3}
}

func (x *ResNotifyTimeLapseOutTime) GetInterval() int32 {
	if x != nil {
		return x.Interval
	}
	return 0
}

func (x *ResNotifyTimeLapseOutTime) GetOutTime() int32 {
	if x != nil {
		return x.OutTime
	}
	return 0
}

func (x *ResNotifyTimeLapseOutTime) GetTotalTime() int32 {
	if x != nil {
		return x.TotalTime
	}
	return 0
}

// 运行状态
type ResNotifyOperationState struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	State OperationState `protobuf:"varint,1,opt,name=state,proto3,enum=OperationState" json:"state,omitempty"`
}

func (x *ResNotifyOperationState) Reset() {
	*x = ResNotifyOperationState{}
	if protoimpl.UnsafeEnabled {
		mi := &file_notify_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResNotifyOperationState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResNotifyOperationState) ProtoMessage() {}

func (x *ResNotifyOperationState) ProtoReflect() protoreflect.Message {
	mi := &file_notify_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResNotifyOperationState.ProtoReflect.Descriptor instead.
func (*ResNotifyOperationState) Descriptor() ([]byte, []int) {
	return file_notify_proto_rawDescGZIP(), []int{4}
}

func (x *ResNotifyOperationState) GetState() OperationState {
	if x != nil {
		return x.State
	}
	return OperationState_OPERATION_STATE_IDLE
}

// 天文校准状态
type ResNotifyStateAstroCalibration struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	State             AstroState `protobuf:"varint,1,opt,name=state,proto3,enum=AstroState" json:"state,omitempty"`
	PlateSolvingTimes int32      `protobuf:"varint,2,opt,name=plate_solving_times,json=plateSolvingTimes,proto3" json:"plate_solving_times,omitempty"`
}

func (x *ResNotifyStateAstroCalibration) Reset() {
	*x = ResNotifyStateAstroCalibration{}
	if protoimpl.UnsafeEnabled {
		mi := &file_notify_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResNotifyStateAstroCalibration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResNotifyStateAstroCalibration) ProtoMessage() {}

func (x *ResNotifyStateAstroCalibration) ProtoReflect() protoreflect.Message {
	mi := &file_notify_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResNotifyStateAstroCalibration.ProtoReflect.Descriptor instead.
func (*ResNotifyStateAstroCalibration) Descriptor() ([]byte, []int) {
	return file_notify_proto_rawDescGZIP(), []int{5}
}

func (x *ResNotifyStateAstroCalibration) GetState() AstroState {
	if x != nil {
		return x.State
	}
	return AstroState_ASTRO_STATE_IDLE
}

func (x *ResNotifyStateAstroCalibration) GetPlateSolvingTimes() int32 {
	if x != nil {
		return x.PlateSolvingTimes
	}
	return 0
}

// 天文GOTO状态
type ResNotifyStateAstroGoto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	State AstroState `protobuf:"varint,1,opt,name=state,proto3,enum=AstroState" json:"state,omitempty"`
}

func (x *ResNotifyStateAstroGoto) Reset() {
	*x = ResNotifyStateAstroGoto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_notify_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResNotifyStateAstroGoto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResNotifyStateAstroGoto) ProtoMessage() {}

func (x *ResNotifyStateAstroGoto) ProtoReflect() protoreflect.Message {
	mi := &file_notify_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResNotifyStateAstroGoto.ProtoReflect.Descriptor instead.
func (*ResNotifyStateAstroGoto) Descriptor() ([]byte, []int) {
	return file_notify_proto_rawDescGZIP(), []int{6}
}

func (x *ResNotifyStateAstroGoto) GetState() AstroState {
	if x != nil {
		return x.State
	}
	return AstroState_ASTRO_STATE_IDLE
}

// 天文跟踪状态
type ResNotifyStateAstroTracking struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	State      OperationState `protobuf:"varint,1,opt,name=state,proto3,enum=OperationState" json:"state,omitempty"`
	TargetName string         `protobuf:"bytes,2,opt,name=target_name,json=targetName,proto3" json:"target_name,omitempty"`
}

func (x *ResNotifyStateAstroTracking) Reset() {
	*x = ResNotifyStateAstroTracking{}
	if protoimpl.UnsafeEnabled {
		mi := &file_notify_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResNotifyStateAstroTracking) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResNotifyStateAstroTracking) ProtoMessage() {}

func (x *ResNotifyStateAstroTracking) ProtoReflect() protoreflect.Message {
	mi := &file_notify_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResNotifyStateAstroTracking.ProtoReflect.Descriptor instead.
func (*ResNotifyStateAstroTracking) Descriptor() ([]byte, []int) {
	return file_notify_proto_rawDescGZIP(), []int{7}
}

func (x *ResNotifyStateAstroTracking) GetState() OperationState {
	if x != nil {
		return x.State
	}
	return OperationState_OPERATION_STATE_IDLE
}

func (x *ResNotifyStateAstroTracking) GetTargetName() string {
	if x != nil {
		return x.TargetName
	}
	return ""
}

// 天文暗场拍摄进度
type ResNotifyProgressCaptureRawDark struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Progress      int32 `protobuf:"varint,1,opt,name=progress,proto3" json:"progress,omitempty"`
	RemainingTime int32 `protobuf:"varint,2,opt,name=remaining_time,json=remainingTime,proto3" json:"remaining_time,omitempty"`
}

func (x *ResNotifyProgressCaptureRawDark) Reset() {
	*x = ResNotifyProgressCaptureRawDark{}
	if protoimpl.UnsafeEnabled {
		mi := &file_notify_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResNotifyProgressCaptureRawDark) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResNotifyProgressCaptureRawDark) ProtoMessage() {}

func (x *ResNotifyProgressCaptureRawDark) ProtoReflect() protoreflect.Message {
	mi := &file_notify_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResNotifyProgressCaptureRawDark.ProtoReflect.Descriptor instead.
func (*ResNotifyProgressCaptureRawDark) Descriptor() ([]byte, []int) {
	return file_notify_proto_rawDescGZIP(), []int{8}
}

func (x *ResNotifyProgressCaptureRawDark) GetProgress() int32 {
	if x != nil {
		return x.Progress
	}
	return 0
}

func (x *ResNotifyProgressCaptureRawDark) GetRemainingTime() int32 {
	if x != nil {
		return x.RemainingTime
	}
	return 0
}

// 天文叠图拍摄进度
type ResNotifyProgressCaptureRawLiveStacking struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TotalCount      int32  `protobuf:"varint,1,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	UpdateCountType int32  `protobuf:"varint,2,opt,name=update_count_type,json=updateCountType,proto3" json:"update_count_type,omitempty"`
	CurrentCount    int32  `protobuf:"varint,3,opt,name=current_count,json=currentCount,proto3" json:"current_count,omitempty"`
	StackedCount    int32  `protobuf:"varint,4,opt,name=stacked_count,json=stackedCount,proto3" json:"stacked_count,omitempty"`
	ExpIndex        int32  `protobuf:"varint,5,opt,name=exp_index,json=expIndex,proto3" json:"exp_index,omitempty"`
	GainIndex       int32  `protobuf:"varint,6,opt,name=gain_index,json=gainIndex,proto3" json:"gain_index,omitempty"`
	TargetName      string `protobuf:"bytes,7,opt,name=target_name,json=targetName,proto3" json:"target_name,omitempty"`
}

func (x *ResNotifyProgressCaptureRawLiveStacking) Reset() {
	*x = ResNotifyProgressCaptureRawLiveStacking{}
	if protoimpl.UnsafeEnabled {
		mi := &file_notify_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResNotifyProgressCaptureRawLiveStacking) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResNotifyProgressCaptureRawLiveStacking) ProtoMessage() {}

func (x *ResNotifyProgressCaptureRawLiveStacking) ProtoReflect() protoreflect.Message {
	mi := &file_notify_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResNotifyProgressCaptureRawLiveStacking.ProtoReflect.Descriptor instead.
func (*ResNotifyProgressCaptureRawLiveStacking) Descriptor() ([]byte, []int) {
	return file_notify_proto_rawDescGZIP(), []int{9}
}

func (x *ResNotifyProgressCaptureRawLiveStacking) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *ResNotifyProgressCaptureRawLiveStacking) GetUpdateCountType() int32 {
	if x != nil {
		return x.UpdateCountType
	}
	return 0
}

func (x *ResNotifyProgressCaptureRawLiveStacking) GetCurrentCount() int32 {
	if x != nil {
		return x.CurrentCount
	}
	return 0
}

func (x *ResNotifyProgressCaptureRawLiveStacking) GetStackedCount() int32 {
	if x != nil {
		return x.StackedCount
	}
	return 0
}

func (x *ResNotifyProgressCaptureRawLiveStacking) GetExpIndex() int32 {
	if x != nil {
		return x.ExpIndex
	}
	return 0
}

func (x *ResNotifyProgressCaptureRawLiveStacking) GetGainIndex() int32 {
	if x != nil {
		return x.GainIndex
	}
	return 0
}

func (x *ResNotifyProgressCaptureRawLiveStacking) GetTargetName() string {
	if x != nil {
		return x.TargetName
	}
	return ""
}

// 参数回显
type ResNotifyParam struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Param []*CommonParam `protobuf:"bytes,1,rep,name=param,proto3" json:"param,omitempty"`
}

func (x *ResNotifyParam) Reset() {
	*x = ResNotifyParam{}
	if protoimpl.UnsafeEnabled {
		mi := &file_notify_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResNotifyParam) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResNotifyParam) ProtoMessage() {}

func (x *ResNotifyParam) ProtoReflect() protoreflect.Message {
	mi := &file_notify_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResNotifyParam.ProtoReflect.Descriptor instead.
func (*ResNotifyParam) Descriptor() ([]byte, []int) {
	return file_notify_proto_rawDescGZIP(), []int{10}
}

func (x *ResNotifyParam) GetParam() []*CommonParam {
	if x != nil {
		return x.Param
	}
	return nil
}

// 摄像头功能状态
type ResNotifyCamFunctionState struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	State      OperationState `protobuf:"varint,1,opt,name=state,proto3,enum=OperationState" json:"state,omitempty"`
	FunctionId uint32         `protobuf:"varint,2,opt,name=function_id,json=functionId,proto3" json:"function_id,omitempty"`
}

func (x *ResNotifyCamFunctionState) Reset() {
	*x = ResNotifyCamFunctionState{}
	if protoimpl.UnsafeEnabled {
		mi := &file_notify_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResNotifyCamFunctionState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResNotifyCamFunctionState) ProtoMessage() {}

func (x *ResNotifyCamFunctionState) ProtoReflect() protoreflect.Message {
	mi := &file_notify_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResNotifyCamFunctionState.ProtoReflect.Descriptor instead.
func (*ResNotifyCamFunctionState) Descriptor() ([]byte, []int) {
	return file_notify_proto_rawDescGZIP(), []int{11}
}

func (x *ResNotifyCamFunctionState) GetState() OperationState {
	if x != nil {
		return x.State
	}
	return OperationState_OPERATION_STATE_IDLE
}

func (x *ResNotifyCamFunctionState) GetFunctionId() uint32 {
	if x != nil {
		return x.FunctionId
	}
	return 0
}

// 连拍进度
type ResNotifyBurstProgress struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TotalCount     uint32 `protobuf:"varint,1,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	CompletedCount uint32 `protobuf:"varint,2,opt,name=completed_count,json=completedCount,proto3" json:"completed_count,omitempty"`
}

func (x *ResNotifyBurstProgress) Reset() {
	*x = ResNotifyBurstProgress{}
	if protoimpl.UnsafeEnabled {
		mi := &file_notify_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResNotifyBurstProgress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResNotifyBurstProgress) ProtoMessage() {}

func (x *ResNotifyBurstProgress) ProtoReflect() protoreflect.Message {
	mi := &file_notify_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResNotifyBurstProgress.ProtoReflect.Descriptor instead.
func (*ResNotifyBurstProgress) Descriptor() ([]byte, []int) {
	return file_notify_proto_rawDescGZIP(), []int{12}
}

func (x *ResNotifyBurstProgress) GetTotalCount() uint32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *ResNotifyBurstProgress) GetCompletedCount() uint32 {
	if x != nil {
		return x.CompletedCount
	}
	return 0
}

// 全景拍摄进度
type ResNotifyPanoramaProgress struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TotalCount     int32 `protobuf:"varint,1,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	CompletedCount int32 `protobuf:"varint,2,opt,name=completed_count,json=completedCount,proto3" json:"completed_count,omitempty"`
}

func (x *ResNotifyPanoramaProgress) Reset() {
	*x = ResNotifyPanoramaProgress{}
	if protoimpl.UnsafeEnabled {
		mi := &file_notify_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResNotifyPanoramaProgress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResNotifyPanoramaProgress) ProtoMessage() {}

func (x *ResNotifyPanoramaProgress) ProtoReflect() protoreflect.Message {
	mi := &file_notify_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResNotifyPanoramaProgress.ProtoReflect.Descriptor instead.
func (*ResNotifyPanoramaProgress) Descriptor() ([]byte, []int) {
	return file_notify_proto_rawDescGZIP(), []int{13}
}

func (x *ResNotifyPanoramaProgress) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *ResNotifyPanoramaProgress) GetCompletedCount() int32 {
	if x != nil {
		return x.CompletedCount
	}
	return 0
}

// 环形灯状态
type ResNotifyRgbState struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	State int32 `protobuf:"varint,1,opt,name=state,proto3" json:"state,omitempty"`
}

func (x *ResNotifyRgbState) Reset() {
	*x = ResNotifyRgbState{}
	if protoimpl.UnsafeEnabled {
		mi := &file_notify_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResNotifyRgbState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResNotifyRgbState) ProtoMessage() {}

func (x *ResNotifyRgbState) ProtoReflect() protoreflect.Message {
	mi := &file_notify_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResNotifyRgbState.ProtoReflect.Descriptor instead.
func (*ResNotifyRgbState) Descriptor() ([]byte, []int) {
	return file_notify_proto_rawDescGZIP(), []int{14}
}

func (x *ResNotifyRgbState) GetState() int32 {
	if x != nil {
		return x.State
	}
	return 0
}

// 电量指示灯状态
type ResNotifyPowerIndState struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	State int32 `protobuf:"varint,1,opt,name=state,proto3" json:"state,omitempty"`
}

func (x *ResNotifyPowerIndState) Reset() {
	*x = ResNotifyPowerIndState{}
	if protoimpl.UnsafeEnabled {
		mi := &file_notify_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResNotifyPowerIndState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResNotifyPowerIndState) ProtoMessage() {}

func (x *ResNotifyPowerIndState) ProtoReflect() protoreflect.Message {
	mi := &file_notify_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResNotifyPowerIndState.ProtoReflect.Descriptor instead.
func (*ResNotifyPowerIndState) Descriptor() ([]byte, []int) {
	return file_notify_proto_rawDescGZIP(), []int{15}
}

func (x *ResNotifyPowerIndState) GetState() int32 {
	if x != nil {
		return x.State
	}
	return 0
}

// websocket主机从机模式状态
type ResNotifyHostSlaveMode struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mode int32 `protobuf:"varint,1,opt,name=mode,proto3" json:"mode,omitempty"`
}

func (x *ResNotifyHostSlaveMode) Reset() {
	*x = ResNotifyHostSlaveMode{}
	if protoimpl.UnsafeEnabled {
		mi := &file_notify_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResNotifyHostSlaveMode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResNotifyHostSlaveMode) ProtoMessage() {}

func (x *ResNotifyHostSlaveMode) ProtoReflect() protoreflect.Message {
	mi := &file_notify_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResNotifyHostSlaveMode.ProtoReflect.Descriptor instead.
func (*ResNotifyHostSlaveMode) Descriptor() ([]byte, []int) {
	return file_notify_proto_rawDescGZIP(), []int{16}
}

func (x *ResNotifyHostSlaveMode) GetMode() int32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

// mtp模式通知
type ResNotifyMTPState struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mode int32 `protobuf:"varint,1,opt,name=mode,proto3" json:"mode,omitempty"`
}

func (x *ResNotifyMTPState) Reset() {
	*x = ResNotifyMTPState{}
	if protoimpl.UnsafeEnabled {
		mi := &file_notify_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResNotifyMTPState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResNotifyMTPState) ProtoMessage() {}

func (x *ResNotifyMTPState) ProtoReflect() protoreflect.Message {
	mi := &file_notify_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResNotifyMTPState.ProtoReflect.Descriptor instead.
func (*ResNotifyMTPState) Descriptor() ([]byte, []int) {
	return file_notify_proto_rawDescGZIP(), []int{17}
}

func (x *ResNotifyMTPState) GetMode() int32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

// 跟踪结果通知
type ResNotifyTrackResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X int32 `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y int32 `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	W int32 `protobuf:"varint,3,opt,name=w,proto3" json:"w,omitempty"`
	H int32 `protobuf:"varint,4,opt,name=h,proto3" json:"h,omitempty"`
}

func (x *ResNotifyTrackResult) Reset() {
	*x = ResNotifyTrackResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_notify_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResNotifyTrackResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResNotifyTrackResult) ProtoMessage() {}

func (x *ResNotifyTrackResult) ProtoReflect() protoreflect.Message {
	mi := &file_notify_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResNotifyTrackResult.ProtoReflect.Descriptor instead.
func (*ResNotifyTrackResult) Descriptor() ([]byte, []int) {
	return file_notify_proto_rawDescGZIP(), []int{18}
}

func (x *ResNotifyTrackResult) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *ResNotifyTrackResult) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *ResNotifyTrackResult) GetW() int32 {
	if x != nil {
		return x.W
	}
	return 0
}

func (x *ResNotifyTrackResult) GetH() int32 {
	if x != nil {
		return x.H
	}
	return 0
}

// cpu mode
type ResNotifyCPUMode struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mode int32 `protobuf:"varint,1,opt,name=mode,proto3" json:"mode,omitempty"`
}

func (x *ResNotifyCPUMode) Reset() {
	*x = ResNotifyCPUMode{}
	if protoimpl.UnsafeEnabled {
		mi := &file_notify_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResNotifyCPUMode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResNotifyCPUMode) ProtoMessage() {}

func (x *ResNotifyCPUMode) ProtoReflect() protoreflect.Message {
	mi := &file_notify_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResNotifyCPUMode.ProtoReflect.Descriptor instead.
func (*ResNotifyCPUMode) Descriptor() ([]byte, []int) {
	return file_notify_proto_rawDescGZIP(), []int{19}
}

func (x *ResNotifyCPUMode) GetMode() int32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

// 日月跟踪通知
type ResNotifyStateAstroTrackingSpecial struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	State      OperationState `protobuf:"varint,1,opt,name=state,proto3,enum=OperationState" json:"state,omitempty"`
	TargetName string         `protobuf:"bytes,2,opt,name=target_name,json=targetName,proto3" json:"target_name,omitempty"`
	Index      int32          `protobuf:"varint,3,opt,name=index,proto3" json:"index,omitempty"`
}

func (x *ResNotifyStateAstroTrackingSpecial) Reset() {
	*x = ResNotifyStateAstroTrackingSpecial{}
	if protoimpl.UnsafeEnabled {
		mi := &file_notify_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResNotifyStateAstroTrackingSpecial) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResNotifyStateAstroTrackingSpecial) ProtoMessage() {}

func (x *ResNotifyStateAstroTrackingSpecial) ProtoReflect() protoreflect.Message {
	mi := &file_notify_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResNotifyStateAstroTrackingSpecial.ProtoReflect.Descriptor instead.
func (*ResNotifyStateAstroTrackingSpecial) Descriptor() ([]byte, []int) {
	return file_notify_proto_rawDescGZIP(), []int{20}
}

func (x *ResNotifyStateAstroTrackingSpecial) GetState() OperationState {
	if x != nil {
		return x.State
	}
	return OperationState_OPERATION_STATE_IDLE
}

func (x *ResNotifyStateAstroTrackingSpecial) GetTargetName() string {
	if x != nil {
		return x.TargetName
	}
	return ""
}

func (x *ResNotifyStateAstroTrackingSpecial) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

// 关机通知
type ResNotifyPowerOff struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ResNotifyPowerOff) Reset() {
	*x = ResNotifyPowerOff{}
	if protoimpl.UnsafeEnabled {
		mi := &file_notify_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResNotifyPowerOff) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResNotifyPowerOff) ProtoMessage() {}

func (x *ResNotifyPowerOff) ProtoReflect() protoreflect.Message {
	mi := &file_notify_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResNotifyPowerOff.ProtoReflect.Descriptor instead.
func (*ResNotifyPowerOff) Descriptor() ([]byte, []int) {
	return file_notify_proto_rawDescGZIP(), []int{21}
}

var File_notify_proto protoreflect.FileDescriptor

var file_notify_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0a,
	0x62, 0x61, 0x73, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x8e, 0x01, 0x0a, 0x18, 0x52,
	0x65, 0x73, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x50, 0x69, 0x63, 0x74, 0x75, 0x72, 0x65, 0x4d,
	0x61, 0x74, 0x63, 0x68, 0x69, 0x6e, 0x67, 0x12, 0x0c, 0x0a, 0x01, 0x78, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x01, 0x78, 0x12, 0x0c, 0x0a, 0x01, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x01, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x77, 0x69, 0x64, 0x74, 0x68, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x05, 0x77, 0x69, 0x64, 0x74, 0x68, 0x12, 0x16, 0x0a, 0x06, 0x68, 0x65, 0x69,
	0x67, 0x68, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68,
	0x74, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x01,
	0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x22, 0x6f, 0x0a, 0x13, 0x52,
	0x65, 0x73, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x53, 0x44, 0x63, 0x61, 0x72, 0x64, 0x49, 0x6e,
	0x66, 0x6f, 0x12, 0x25, 0x0a, 0x0e, 0x61, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x5f,
	0x73, 0x69, 0x7a, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0d, 0x61, 0x76, 0x61, 0x69,
	0x6c, 0x61, 0x62, 0x6c, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x74, 0x6f, 0x74,
	0x61, 0x6c, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x74,
	0x6f, 0x74, 0x61, 0x6c, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x22, 0x36, 0x0a, 0x13,
	0x52, 0x65, 0x73, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x54,
	0x69, 0x6d, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x5f, 0x74, 0x69,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64,
	0x54, 0x69, 0x6d, 0x65, 0x22, 0x71, 0x0a, 0x19, 0x52, 0x65, 0x73, 0x4e, 0x6f, 0x74, 0x69, 0x66,
	0x79, 0x54, 0x69, 0x6d, 0x65, 0x4c, 0x61, 0x70, 0x73, 0x65, 0x4f, 0x75, 0x74, 0x54, 0x69, 0x6d,
	0x65, 0x12, 0x1a, 0x0a, 0x08, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x76, 0x61, 0x6c, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x08, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x76, 0x61, 0x6c, 0x12, 0x19, 0x0a,
	0x08, 0x6f, 0x75, 0x74, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x07, 0x6f, 0x75, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x74, 0x6f, 0x74, 0x61,
	0x6c, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x74, 0x6f,
	0x74, 0x61, 0x6c, 0x54, 0x69, 0x6d, 0x65, 0x22, 0x40, 0x0a, 0x17, 0x52, 0x65, 0x73, 0x4e, 0x6f,
	0x74, 0x69, 0x66, 0x79, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61,
	0x74, 0x65, 0x12, 0x25, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x0f, 0x2e, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61,
	0x74, 0x65, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x22, 0x73, 0x0a, 0x1e, 0x52, 0x65, 0x73,
	0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x53, 0x74, 0x61, 0x74, 0x65, 0x41, 0x73, 0x74, 0x72, 0x6f,
	0x43, 0x61, 0x6c, 0x69, 0x62, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x21, 0x0a, 0x05, 0x73,
	0x74, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0b, 0x2e, 0x41, 0x73, 0x74,
	0x72, 0x6f, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x12, 0x2e,
	0x0a, 0x13, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x5f, 0x73, 0x6f, 0x6c, 0x76, 0x69, 0x6e, 0x67, 0x5f,
	0x74, 0x69, 0x6d, 0x65, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x11, 0x70, 0x6c, 0x61,
	0x74, 0x65, 0x53, 0x6f, 0x6c, 0x76, 0x69, 0x6e, 0x67, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x22, 0x3c,
	0x0a, 0x17, 0x52, 0x65, 0x73, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x53, 0x74, 0x61, 0x74, 0x65,
	0x41, 0x73, 0x74, 0x72, 0x6f, 0x47, 0x6f, 0x74, 0x6f, 0x12, 0x21, 0x0a, 0x05, 0x73, 0x74, 0x61,
	0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0b, 0x2e, 0x41, 0x73, 0x74, 0x72, 0x6f,
	0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x22, 0x65, 0x0a, 0x1b,
	0x52, 0x65, 0x73, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x53, 0x74, 0x61, 0x74, 0x65, 0x41, 0x73,
	0x74, 0x72, 0x6f, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x69, 0x6e, 0x67, 0x12, 0x25, 0x0a, 0x05, 0x73,
	0x74, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0f, 0x2e, 0x4f, 0x70, 0x65,
	0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x05, 0x73, 0x74, 0x61,
	0x74, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x5f, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x4e,
	0x61, 0x6d, 0x65, 0x22, 0x64, 0x0a, 0x1f, 0x52, 0x65, 0x73, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79,
	0x50, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x43, 0x61, 0x70, 0x74, 0x75, 0x72, 0x65, 0x52,
	0x61, 0x77, 0x44, 0x61, 0x72, 0x6b, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x67, 0x72, 0x65,
	0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x67, 0x72, 0x65,
	0x73, 0x73, 0x12, 0x25, 0x0a, 0x0e, 0x72, 0x65, 0x6d, 0x61, 0x69, 0x6e, 0x69, 0x6e, 0x67, 0x5f,
	0x74, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0d, 0x72, 0x65, 0x6d, 0x61,
	0x69, 0x6e, 0x69, 0x6e, 0x67, 0x54, 0x69, 0x6d, 0x65, 0x22, 0x9d, 0x02, 0x0a, 0x27, 0x52, 0x65,
	0x73, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x50, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x43,
	0x61, 0x70, 0x74, 0x75, 0x72, 0x65, 0x52, 0x61, 0x77, 0x4c, 0x69, 0x76, 0x65, 0x53, 0x74, 0x61,
	0x63, 0x6b, 0x69, 0x6e, 0x67, 0x12, 0x1f, 0x0a, 0x0b, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x74, 0x6f, 0x74, 0x61,
	0x6c, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x2a, 0x0a, 0x11, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x0f, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x54, 0x79,
	0x70, 0x65, 0x12, 0x23, 0x0a, 0x0d, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x5f, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x63, 0x75, 0x72, 0x72, 0x65,
	0x6e, 0x74, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x23, 0x0a, 0x0d, 0x73, 0x74, 0x61, 0x63, 0x6b,
	0x65, 0x64, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c,
	0x73, 0x74, 0x61, 0x63, 0x6b, 0x65, 0x64, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1b, 0x0a, 0x09,
	0x65, 0x78, 0x70, 0x5f, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x08, 0x65, 0x78, 0x70, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x1d, 0x0a, 0x0a, 0x67, 0x61, 0x69,
	0x6e, 0x5f, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x67,
	0x61, 0x69, 0x6e, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x1f, 0x0a, 0x0b, 0x74, 0x61, 0x72, 0x67,
	0x65, 0x74, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x74,
	0x61, 0x72, 0x67, 0x65, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x34, 0x0a, 0x0e, 0x52, 0x65, 0x73,
	0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x12, 0x22, 0x0a, 0x05, 0x70,
	0x61, 0x72, 0x61, 0x6d, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x43, 0x6f, 0x6d,
	0x6d, 0x6f, 0x6e, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x52, 0x05, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x22,
	0x63, 0x0a, 0x19, 0x52, 0x65, 0x73, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x43, 0x61, 0x6d, 0x46,
	0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x25, 0x0a, 0x05,
	0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0f, 0x2e, 0x4f, 0x70,
	0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x05, 0x73, 0x74,
	0x61, 0x74, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x66, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f,
	0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x66, 0x75, 0x6e, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x49, 0x64, 0x22, 0x62, 0x0a, 0x16, 0x52, 0x65, 0x73, 0x4e, 0x6f, 0x74, 0x69, 0x66,
	0x79, 0x42, 0x75, 0x72, 0x73, 0x74, 0x50, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x12, 0x1f,
	0x0a, 0x0b, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x0a, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12,
	0x27, 0x0a, 0x0f, 0x63, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x5f, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0e, 0x63, 0x6f, 0x6d, 0x70, 0x6c, 0x65,
	0x74, 0x65, 0x64, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x65, 0x0a, 0x19, 0x52, 0x65, 0x73, 0x4e,
	0x6f, 0x74, 0x69, 0x66, 0x79, 0x50, 0x61, 0x6e, 0x6f, 0x72, 0x61, 0x6d, 0x61, 0x50, 0x72, 0x6f,
	0x67, 0x72, 0x65, 0x73, 0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x74, 0x6f, 0x74, 0x61,
	0x6c, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x27, 0x0a, 0x0f, 0x63, 0x6f, 0x6d, 0x70, 0x6c, 0x65,
	0x74, 0x65, 0x64, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x0e, 0x63, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x22,
	0x29, 0x0a, 0x11, 0x52, 0x65, 0x73, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x52, 0x67, 0x62, 0x53,
	0x74, 0x61, 0x74, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x22, 0x2e, 0x0a, 0x16, 0x52, 0x65,
	0x73, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x50, 0x6f, 0x77, 0x65, 0x72, 0x49, 0x6e, 0x64, 0x53,
	0x74, 0x61, 0x74, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x22, 0x2c, 0x0a, 0x16, 0x52, 0x65,
	0x73, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x48, 0x6f, 0x73, 0x74, 0x53, 0x6c, 0x61, 0x76, 0x65,
	0x4d, 0x6f, 0x64, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6d, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x04, 0x6d, 0x6f, 0x64, 0x65, 0x22, 0x27, 0x0a, 0x11, 0x52, 0x65, 0x73, 0x4e,
	0x6f, 0x74, 0x69, 0x66, 0x79, 0x4d, 0x54, 0x50, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x6d, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x6d, 0x6f, 0x64,
	0x65, 0x22, 0x4e, 0x0a, 0x14, 0x52, 0x65, 0x73, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x54, 0x72,
	0x61, 0x63, 0x6b, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x0c, 0x0a, 0x01, 0x78, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x01, 0x78, 0x12, 0x0c, 0x0a, 0x01, 0x79, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x01, 0x79, 0x12, 0x0c, 0x0a, 0x01, 0x77, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x01, 0x77, 0x12, 0x0c, 0x0a, 0x01, 0x68, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x01,
	0x68, 0x22, 0x26, 0x0a, 0x10, 0x52, 0x65, 0x73, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x43, 0x50,
	0x55, 0x4d, 0x6f, 0x64, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6d, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x04, 0x6d, 0x6f, 0x64, 0x65, 0x22, 0x82, 0x01, 0x0a, 0x22, 0x52, 0x65,
	0x73, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x53, 0x74, 0x61, 0x74, 0x65, 0x41, 0x73, 0x74, 0x72,
	0x6f, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x69, 0x6e, 0x67, 0x53, 0x70, 0x65, 0x63, 0x69, 0x61, 0x6c,
	0x12, 0x25, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x0f, 0x2e, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x65,
	0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x74, 0x61, 0x72, 0x67, 0x65,
	0x74, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x74, 0x61,
	0x72, 0x67, 0x65, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e, 0x64, 0x65,
	0x78, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x22, 0x13,
	0x0a, 0x11, 0x52, 0x65, 0x73, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x50, 0x6f, 0x77, 0x65, 0x72,
	0x4f, 0x66, 0x66, 0x2a, 0x95, 0x01, 0x0a, 0x05, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x0e, 0x0a,
	0x0a, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f, 0x49, 0x44, 0x4c, 0x45, 0x10, 0x00, 0x12, 0x11, 0x0a,
	0x0d, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f, 0x52, 0x55, 0x4e, 0x4e, 0x49, 0x4e, 0x47, 0x10, 0x01,
	0x12, 0x12, 0x0a, 0x0e, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f, 0x53, 0x54, 0x4f, 0x50, 0x50, 0x49,
	0x4e, 0x47, 0x10, 0x02, 0x12, 0x11, 0x0a, 0x0d, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f, 0x53, 0x54,
	0x4f, 0x50, 0x50, 0x45, 0x44, 0x10, 0x03, 0x12, 0x11, 0x0a, 0x0d, 0x53, 0x54, 0x41, 0x54, 0x45,
	0x5f, 0x53, 0x55, 0x43, 0x43, 0x45, 0x53, 0x53, 0x10, 0x04, 0x12, 0x10, 0x0a, 0x0c, 0x53, 0x54,
	0x41, 0x54, 0x45, 0x5f, 0x46, 0x41, 0x49, 0x4c, 0x45, 0x44, 0x10, 0x05, 0x12, 0x1d, 0x0a, 0x19,
	0x53, 0x54, 0x41, 0x54, 0x45, 0x5f, 0x41, 0x53, 0x54, 0x52, 0x4f, 0x5f, 0x50, 0x4c, 0x41, 0x54,
	0x45, 0x5f, 0x53, 0x4f, 0x4c, 0x56, 0x49, 0x4e, 0x47, 0x10, 0x06, 0x2a, 0x82, 0x01, 0x0a, 0x0e,
	0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x18,
	0x0a, 0x14, 0x4f, 0x50, 0x45, 0x52, 0x41, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x53, 0x54, 0x41, 0x54,
	0x45, 0x5f, 0x49, 0x44, 0x4c, 0x45, 0x10, 0x00, 0x12, 0x1b, 0x0a, 0x17, 0x4f, 0x50, 0x45, 0x52,
	0x41, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f, 0x52, 0x55, 0x4e, 0x4e,
	0x49, 0x4e, 0x47, 0x10, 0x01, 0x12, 0x1c, 0x0a, 0x18, 0x4f, 0x50, 0x45, 0x52, 0x41, 0x54, 0x49,
	0x4f, 0x4e, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f, 0x53, 0x54, 0x4f, 0x50, 0x50, 0x49, 0x4e,
	0x47, 0x10, 0x02, 0x12, 0x1b, 0x0a, 0x17, 0x4f, 0x50, 0x45, 0x52, 0x41, 0x54, 0x49, 0x4f, 0x4e,
	0x5f, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f, 0x53, 0x54, 0x4f, 0x50, 0x50, 0x45, 0x44, 0x10, 0x03,
	0x2a, 0x8d, 0x01, 0x0a, 0x0a, 0x41, 0x73, 0x74, 0x72, 0x6f, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12,
	0x14, 0x0a, 0x10, 0x41, 0x53, 0x54, 0x52, 0x4f, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f, 0x49,
	0x44, 0x4c, 0x45, 0x10, 0x00, 0x12, 0x17, 0x0a, 0x13, 0x41, 0x53, 0x54, 0x52, 0x4f, 0x5f, 0x53,
	0x54, 0x41, 0x54, 0x45, 0x5f, 0x52, 0x55, 0x4e, 0x4e, 0x49, 0x4e, 0x47, 0x10, 0x01, 0x12, 0x18,
	0x0a, 0x14, 0x41, 0x53, 0x54, 0x52, 0x4f, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f, 0x53, 0x54,
	0x4f, 0x50, 0x50, 0x49, 0x4e, 0x47, 0x10, 0x02, 0x12, 0x17, 0x0a, 0x13, 0x41, 0x53, 0x54, 0x52,
	0x4f, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f, 0x53, 0x54, 0x4f, 0x50, 0x50, 0x45, 0x44, 0x10,
	0x03, 0x12, 0x1d, 0x0a, 0x19, 0x41, 0x53, 0x54, 0x52, 0x4f, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x45,
	0x5f, 0x50, 0x4c, 0x41, 0x54, 0x45, 0x5f, 0x53, 0x4f, 0x4c, 0x56, 0x49, 0x4e, 0x47, 0x10, 0x04,
	0x42, 0x1b, 0x5a, 0x19, 0x76, 0x70, 0x72, 0x65, 0x6e, 0x6e, 0x65, 0x72, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x64, 0x77, 0x61, 0x72, 0x66, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_notify_proto_rawDescOnce sync.Once
	file_notify_proto_rawDescData = file_notify_proto_rawDesc
)

func file_notify_proto_rawDescGZIP() []byte {
	file_notify_proto_rawDescOnce.Do(func() {
		file_notify_proto_rawDescData = protoimpl.X.CompressGZIP(file_notify_proto_rawDescData)
	})
	return file_notify_proto_rawDescData
}

var file_notify_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_notify_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_notify_proto_goTypes = []interface{}{
	(State)(0),                                      // 0: State
	(OperationState)(0),                             // 1: OperationState
	(AstroState)(0),                                 // 2: AstroState
	(*ResNotifyPictureMatching)(nil),                // 3: ResNotifyPictureMatching
	(*ResNotifySDcardInfo)(nil),                     // 4: ResNotifySDcardInfo
	(*ResNotifyRecordTime)(nil),                     // 5: ResNotifyRecordTime
	(*ResNotifyTimeLapseOutTime)(nil),               // 6: ResNotifyTimeLapseOutTime
	(*ResNotifyOperationState)(nil),                 // 7: ResNotifyOperationState
	(*ResNotifyStateAstroCalibration)(nil),          // 8: ResNotifyStateAstroCalibration
	(*ResNotifyStateAstroGoto)(nil),                 // 9: ResNotifyStateAstroGoto
	(*ResNotifyStateAstroTracking)(nil),             // 10: ResNotifyStateAstroTracking
	(*ResNotifyProgressCaptureRawDark)(nil),         // 11: ResNotifyProgressCaptureRawDark
	(*ResNotifyProgressCaptureRawLiveStacking)(nil), // 12: ResNotifyProgressCaptureRawLiveStacking
	(*ResNotifyParam)(nil),                          // 13: ResNotifyParam
	(*ResNotifyCamFunctionState)(nil),               // 14: ResNotifyCamFunctionState
	(*ResNotifyBurstProgress)(nil),                  // 15: ResNotifyBurstProgress
	(*ResNotifyPanoramaProgress)(nil),               // 16: ResNotifyPanoramaProgress
	(*ResNotifyRgbState)(nil),                       // 17: ResNotifyRgbState
	(*ResNotifyPowerIndState)(nil),                  // 18: ResNotifyPowerIndState
	(*ResNotifyHostSlaveMode)(nil),                  // 19: ResNotifyHostSlaveMode
	(*ResNotifyMTPState)(nil),                       // 20: ResNotifyMTPState
	(*ResNotifyTrackResult)(nil),                    // 21: ResNotifyTrackResult
	(*ResNotifyCPUMode)(nil),                        // 22: ResNotifyCPUMode
	(*ResNotifyStateAstroTrackingSpecial)(nil),      // 23: ResNotifyStateAstroTrackingSpecial
	(*ResNotifyPowerOff)(nil),                       // 24: ResNotifyPowerOff
	(*CommonParam)(nil),                             // 25: CommonParam
}
var file_notify_proto_depIdxs = []int32{
	1,  // 0: ResNotifyOperationState.state:type_name -> OperationState
	2,  // 1: ResNotifyStateAstroCalibration.state:type_name -> AstroState
	2,  // 2: ResNotifyStateAstroGoto.state:type_name -> AstroState
	1,  // 3: ResNotifyStateAstroTracking.state:type_name -> OperationState
	25, // 4: ResNotifyParam.param:type_name -> CommonParam
	1,  // 5: ResNotifyCamFunctionState.state:type_name -> OperationState
	1,  // 6: ResNotifyStateAstroTrackingSpecial.state:type_name -> OperationState
	7,  // [7:7] is the sub-list for method output_type
	7,  // [7:7] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_notify_proto_init() }
func file_notify_proto_init() {
	if File_notify_proto != nil {
		return
	}
	file_base_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_notify_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResNotifyPictureMatching); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_notify_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResNotifySDcardInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_notify_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResNotifyRecordTime); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_notify_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResNotifyTimeLapseOutTime); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_notify_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResNotifyOperationState); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_notify_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResNotifyStateAstroCalibration); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_notify_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResNotifyStateAstroGoto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_notify_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResNotifyStateAstroTracking); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_notify_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResNotifyProgressCaptureRawDark); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_notify_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResNotifyProgressCaptureRawLiveStacking); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_notify_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResNotifyParam); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_notify_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResNotifyCamFunctionState); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_notify_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResNotifyBurstProgress); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_notify_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResNotifyPanoramaProgress); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_notify_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResNotifyRgbState); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_notify_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResNotifyPowerIndState); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_notify_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResNotifyHostSlaveMode); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_notify_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResNotifyMTPState); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_notify_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResNotifyTrackResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_notify_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResNotifyCPUMode); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_notify_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResNotifyStateAstroTrackingSpecial); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_notify_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResNotifyPowerOff); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_notify_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_notify_proto_goTypes,
		DependencyIndexes: file_notify_proto_depIdxs,
		EnumInfos:         file_notify_proto_enumTypes,
		MessageInfos:      file_notify_proto_msgTypes,
	}.Build()
	File_notify_proto = out.File
	file_notify_proto_rawDesc = nil
	file_notify_proto_goTypes = nil
	file_notify_proto_depIdxs = nil
}
